### ISSUE TITLE
Strange performance issue after 5 second idle

### ISSUE THREAD

**Issue by jeff-h** [laradock/laradock#1227]
### Info:
- Docker version: Docker version 17.09.0-ce, build afdb6d4
- Laradock commit: d349c20ff5cfe004c429bdc404fdacd9c123b591
- System info: MacBook Pro i5 / 8GB RAM 
- System info: macOS High Sierra 10.13 

I'm using Laradock's built-in support for docker-sync, and I'm also using xdebug, in case that's relevant.

### Issue:
My site's first page load is slow (on this heavy Drupal site, 11 seconds). Subsequent page loads are fast — around 1.6 seconds (very impressive, I think, for this site). If I reload over and over, I get the fast speed very consistently.

**However** — if I wait for 5 or more seconds before reloading, the page load reverts to the slow 11 seconds time, just once. Quick reloads after that are back to the fast speed. Any time I leave it longer than 5 seconds (which basically is almost always, during development) I get the slow load time.

My colleague's MacBook Pro 15 gets much faster page loads than my Mac, but he also sees about a 20% slowdown on any page load after a 5 second idle time.
_____

### Expected behavior:

I'd expect it to be slow when warming up caches, I guess, but after that, fast all the time.
_____

**Comment by mgralikowski** [comment]
Hi,

Same issue but this time with Windows 10. First load about 10 second, next about 1 sec. I hear my CPU during loading after longer break. I have also installed PHPMyAdmin and it works super fast. The problem is only with site (nginx) and after longer break (~3 minutes).

![screenshot_3](https://user-images.githubusercontent.com/17027876/32945073-58a5a1fa-cb92-11e7-9451-0d628e722fcc.png)
