### ISSUE TITLE
how to run php worker

### ISSUE THREAD

**Issue by foxtech9** [laradock/laradock#1367]
No queues are working. I run the _docker-compose up -d php-worker_. I include the _php artisan queue: work_ command. I want to send a job in a queue and nothing. Also used as sync, database, redis, beanstalkd. Where can I read the logs or some information does not work?

**Comment by foxtech9** [comment]
Solved the problem

**Comment by evantolorio** [comment]
If someone hasn't found a solution yet, maybe this could help. You should edit the php-worker/supervisord.conf file to whatever your system architecture is set up.

In my case, since I use Redis queue driver and have a multiple projects setup, 

`command=php /var/www/artisan queue:work --sleep=3 --tries=3 --daemon`

would be

`command=php /var/www/<project_name>/artisan queue:work redis --sleep=3 --tries=3 --daemon`

It worked for me. :)

**Comment by Alexanderwmc** [comment]
Same question! I wrote my supervisor configure file `project.conf` in `/etc/supervisor/conf.d/` of container `php-worker`, like this:
```
[program:project]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/project/artisan queue:work sqs --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/project/worker.log

```

and i restart the container. It gave me an error:
```
2018-08-07 04:50:48,186 INFO exited: laravel-worker_00 (exit status 1; not expected)
2018-08-07 04:50:49,188 INFO gave up: laravel-worker_00 entered FATAL state, too many start retries too quickly
```

**Comment by aconital** [comment]
@Alexanderwmc did you manage to fix it by any chance?

**Comment by BalaWxd** [comment]
@evantolorio's solution fixed my problem.

I am using phpredis and when supervisor spawn the queue worker with using phpredis as client, it fails immediately, the stderr logs shows @Alexanderwmc posted. 

Running below command from php-worker container can get you more information about the queue:work failure raising from laravel.

`docker-compose -p <namespace> exce php-worker php /var/www/<project>/artisan queue:work`, the output I get is something like 
`Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Illuminate\Support\Facades\Redis::connect()`. This confirms for me, I need to install phpredis on the container.

**Comment by mlars84** [comment]
Anyone have any insights for this error?
`Step 15/18 : COPY supervisord.conf /etc/supervisord.conf
ERROR: Service 'php-worker' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder254682604/supervisord.conf: no such file or directory`
I'm setting my php-worker pretty close to the laradock version. Here is my docker-compose.yml:
`### PHP Worker
  php-worker:
    build:
      context: .
      dockerfile: .docker/php-worker/Dockerfile
    volumes:
      - ./docker/php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - redis
    networks:
      - app-tier`
app-tier includes my php-fpm container. Redis is up and running. I added redis to the php-worker Docker-file as well:
`# Install Redis
ARG INSTALL_PHPREDIS=false
ENV INSTALL_PHPREDIS ${INSTALL_PHPREDIS}
RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    # Install Php Redis extension
    pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis \
;fi`
I'm not even getting to the artisan command in my laravel-worker.conf yet.

**Comment by dakong-yi** [comment]
My process started normally, but I don't process the queue. What could be the reason?
 ```php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_03 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_04 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_05 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_06 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-worker_1           | 2019-01-25 10:48:07,468 INFO success: laravel-worker_07 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by GarridoM** [comment]
I have the same problem. I see all the process but when i throw the job, its state is always processing. What is happening?

**Comment by kiankji** [comment]
It seems to be a permission problem. When I set the user from laradock to root everything worked fine.

`[program:image-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/laravel-app/artisan queue:work redis --tries=3 --daemon
autostart=true
autorestart=true
numprocs=2
**user=root**
redirect_stderr=true
stdout_logfile=/var/www/laravel-app/worker.log
`

**Comment by evantolorio** [comment]
Yes, you should also be mindful of the user running the command

**Comment by shaneparsons** [comment]
@evantolorio for the "multiple project" setup, how would you handle the conf files if multiple projects needed it? Would you create a .conf per project (e.g. `site1.conf` `site2.conf`) or is there a better way?

**Comment by evantolorio** [comment]
Hi @shaneparsons. It depends on what you need but in my case, one file is enough since it's the supervisord's config I am manipulating. I don't want the config to be cluttered. Nevertheless, if you choose to go for multiple files just make sure that you include all of it to be run in the container.

**Comment by Stone624** [comment]
Hello! In case anyone is looking for an answer to this issue more generally, I think I've just found it -- It's an issue with my Dockerfile.

as a NOTE : I am not using Laradock, NOR am I using Supervisor, so none of these proposed solutions worked for me. I am also not using a single BASH script that Switches a CONTAINER_ROLE variable to decide which command to run.

I have 3 separate Dockerfiles, One for an Apache Web Server, One for Laravel's Scheduler, and One for Laravel's Queue Worker, and am using Docker-compose to combine them with a Mysql and Redis images.
My Web Server using "FROM php:7.4-apache" (with some setup), as well as my Scheduler with command `CMD ["cron", "-f"]` worked as expected -- I can see Web Access and Scheduled commands running from the Docker-compose foreground prompts.
However the Queue worker, with command `CMD ["php", "artisan", "queue:work"]`, Although Running without issue within docker-compose, Didn't actually serve any jobs coming into Redis from the other containers. I bash'd into the Queue worker Container and ran "php artisan queue:work" and it started processing from there just fine.

The Solution is to change
`
CMD ["php", "artisan", "queue:work"]
`
To
`
ENTRYPOINT ["php", "artisan", "queue:work"]
`
With Entrypoint instead of Cmd, The Jobs from my scheduler started being executed by the Queue Worker Container automatically.

I Hope this can help someone else!

/Mini-Rant/ Regarding Supervisor for those interested, As Docker is supposed to be a "Single Command Execution" environment, It's seems to be pretty poor practice to use Something like Supervisor to keep alive a command whose termination is supposed to kill the entire docker container. Instead of restoring a failed Queue Worker, Spin up a new Docker Container. /End Mini-rant/

**Comment by manusiakemos** [comment]
Install supervisor first in your container.

Install Supervisor[#](https://laradock.io/documentation/#install-supervisor)
Supervisor is a client/server system that allows its users to monitor and control a number of processes on UNIX-like operating systems.

(see http://supervisord.org/index.html)

To install Supervisor in the Workspace container

1 - Open the .env file

2 - Set WORKSPACE_INSTALL_SUPERVISOR and WORKSPACE_INSTALL_PYTHON to true.

3 - Create supervisor configuration file (for ex., named laravel-worker.conf) for Laravel Queue Worker in php-worker/supervisord.d/ by simply copy from laravel-worker.conf.example

4 - Re-build the container docker-compose build workspace Or docker-compose up --build -d workspace

**Comment by zelucena** [comment]
Same for me using pgsql. The error message is very subtle because it only states that the work run for > 1 second.
If you enter the container `docker compose exec php-worker sh` and enter the project folder `/var/www` you can try commands. `php artisan queue:monitor default`
If you get an error "driver not found": check your .env. This is the portion in php-worker Dockerfile. You can run manually from the container.
# Install PostgreSQL drivers:
ARG INSTALL_PGSQL=false
RUN if [ ${INSTALL_PGSQL} = true ]; then \
  apk --update add postgresql-dev \
  && docker-php-ext-install pdo_pgsql \
  ;fi
