### ISSUE TITLE
Add Crontab and Supervisor

### ISSUE THREAD

**Issue by nickfan** [laradock/laradock#14]
add crontab and supervisor support

if we need to run a full-featured laravel application
we need to add laravel crontab setting to system . reference: [https://laravel.com/docs/5.2/scheduling](https://laravel.com/docs/5.2/scheduling)

eg:

```
* * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1
```

and optionally we need to add The Queue Listener to the System by supervisor .
reference: [https://laravel.com/docs/5.2/queues#supervisor-configuration](https://laravel.com/docs/5.2/queues#supervisor-configuration)

eg:

```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/forge/app.com/artisan queue:work sqs --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=forge
numprocs=8
redirect_stderr=true
stdout_logfile=/home/forge/app.com/worker.log
```

if we have multiple application we may need a mapping folder like nginx site-avaiable to store supervisor conf.d config files.

**Comment by tripper54** [comment]
Note rather than using supervisord you could use phusion's provided runit process manager to run a daemonized version of the listener, see 
https://laravel.com/docs/5.2/queues#daemon-queue-listener

There could even be a case for running this in a seperate container.

**Comment by Lednerb** [comment]
In which container would you install the crontab?

On production server you may have no `workspace` container.

By the naming the `application` container would be the best one but it's only holding application data and is not running all the time.

The `nginx` container has to handle the webserver-thing, not really cron-specific things.

Than there's only the `php-fpm` container left.

What do you think?

**Comment by Mahmoudz** [comment]
@Lednerb I think you should create a container for it. Like any other service, that could be turned on and off whenever needed.

**Comment by francislavoie** [comment]
I'm new to docker. I need to run a work queue but I'm not exactly sure what this new container should like as you suggest @Mahmoudz. Could you point me in the right direction?

**Comment by Mahmoudz** [comment]
I can't remember when it was the last time I used beanstalkd. We do have support for `beanstalkd` in LaraDock [https://github.com/LaraDock/laradock/blob/master/beanstalkd/Dockerfile](https://github.com/LaraDock/laradock/blob/master/beanstalkd/Dockerfile), maybe looking at that container would give you some hintes. However, I suggest you create an issue stating clearly what you need help with, and hopefully someone familiar with it can provide you with the help needed.

**Comment by francislavoie** [comment]
Yeah I have beanstalkd running, I meant how should I start the laravel work daemon, i.e. `php artisan queue:work beanstalkd --daemon`. This needs to be run from a container that has both PHP-cli and the application code available to it but I'm not sure how to set this up.

**Comment by Mahmoudz** [comment]
The PHP-CLI is on the Workspace Container, I think you should start looking there, you might need to run your command from that Container. The Laravel code is mapped and accessible from that Container.

**Comment by philtrep** [comment]
We now have crontab available in the `workspace` container, this solves the first part of this issue.

**Comment by sixlive** [comment]
So I see that crontab is available and setup by default in the workspace container, however I still need to edit the crontab through the container once it's running to activate it. Am I missing something, is this by design or is this a new issue?

**Comment by philtrep** [comment]
@sixlive You can edit the crontab file in your clone of LaraDock at `workspace/crontab/root` https://github.com/laradock/laradock/blob/master/workspace/crontab/root before creating the containers.

**Comment by francislavoie** [comment]
Also alternatively you can set up a volume for a crontab file, i.e. `./workspace/crontab/root:/var/spool/cron/crontabs/root` and your changes will be updated live, no need to rebuild the container.

**Comment by sixlive** [comment]
Right, its setup but it never runs until I edit it inside the workspace container, I think it has to do with it being installed after its edited via `crontab -e`

**Comment by philtrep** [comment]
@sixlive Okay that could be an issue then, I tested it when I added the functionality and it was running without being required to run `crontab -e` as far as I can remember.

**Comment by sixlive** [comment]
@philtrep it does this on three different configurations and builds that we are currently using so it appears to be consistent from where I'm standing. Each time they immediately start running after just running `crontab -e` and exiting.

**Comment by philtrep** [comment]
@sixlive Okay it's most certainly a bug then, please create a separate issue for this.

**Comment by edmundluong** [comment]
@philtrep @Mahmoudz @appleboy 

What is the status of this issue? I see that we now have crontab support for scheduling, but do we have the supervisor support for managing queue workers?

If not, I can take a closer look at this since this is a pretty important feature IMO. I am envisioning this will be something added to the workspace container but I am not too sure on that, thoughts?

**Comment by philtrep** [comment]
@edmundluong This issue is very much still open. As far as I know, we do not currently have supervisor support.

If you feel like submitting a PR go for it, this issue seems pretty popular so it's definitely something important to some users.

According to https://github.com/phusion/baseimage-docker/issues/164, the parent(?) image of the `laradock/workspace` image (`phusion/baseimage`) uses `runit`, could it be a viable alternative to `supervisor`?

**Comment by florentb** [comment]
For the queue part, I've simply added a service to the stack:

```yml
php-worker:
    build:
      context: ./php-fpm
    volumes_from:
      - application
    command: php artisan queue:work
```

**Comment by cjmaxik** [comment]
@florentb Can you give a little more information about your php-worker? What is the Dockerfile?

**Comment by Lednerb** [comment]
@cjmaxik he uses the `php-fpm` Dockerfile and image and just creates a new container with the `php artisan queue:work` command.

It's like a second command that runs the worker in the _background_.

**Comment by florentb** [comment]
@cjmaxik In my setup, I use Nginx with PHP-FPM. The PHP-FPM build has a PHP cli so I use the same Dockerfile in the worker. I only override the default command. This way, the worker configuration is the same as the server configuration (same PHP version, same ini, etc.). 

Supervisor is only useful if you to have handle multiple processes within the same Docker command.

However I wonder if `queue:listen` (instead of `queue:work`) wouldn't a better choice (Anyone on this?)

**Comment by cjmaxik** [comment]
@florentb so, I need to simple copy `php-fpm` directory in `php-worker` and add your settings in compose, right?

About `listen`: 
> The queue:work Artisan command includes a --daemon option for forcing the queue worker to continue processing jobs without ever re-booting the framework. **This results in a significant reduction of CPU usage when compared to the queue:listen command:**
So, `queue:work` is preferable.

**Comment by florentb** [comment]
@cjmaxik You don't have to copy anything if you use Laradock. The directory already exists. Just add those lines (and the `env` you want) to the services section of your `docker-compose.yml` file.

**Comment by cjmaxik** [comment]
@florentb Thanks, I just needed to pass Dockerfile name (or just simply rename 70 file) and it works. Thanks again.

**Comment by MPJHorner** [comment]
As cron/queueworker and required for every production environment. It would be good to get a clear understanding of what the best way to achieve this is. I currently have cron (biggest nightmare with env variables) running under supervisor and queue run straight off command.

**Comment by ydatech** [comment]
I still have this issue.

This is my cron script:
```
* * * * * laradock php /var/www/magento-melisa/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/magento-melisa/var/log/magento.cron.log
* * * * * laradock php /var/www/magento-melisa/update/cron.php >> /var/www/magento-melisa/var/log/update.cron.log
* * * * * laradock php /var/www/magento-melisa/bin/magento setup:cron:run >> /var/www/magento-melisa/var/log/setup.cron.log
```

**Comment by ryancwalsh** [comment]
@Mahmoudz I see that you closed this issue, but I don't see what the solution is.

Now that I've run `docker-compose up -d nginx mysql redis php-worker`, **how can I configure Supervisor, and how can I start it?**

I see some [defaults here](https://github.com/laradock/laradock/blob/master/php-worker/supervisord.d/laravel-worker.conf), which is cool.

https://laravel.com/docs/5.6/queues#supervisor-configuration says I need to run:

```
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start laravel-worker:*
```

So I figured I'd enter the "php-worker" container with `docker-compose exec php-worker bash` (since `docker-compose exec workspace bash` is how I've learned to get into the "workspace" container).

But I see `OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

Thanks so much for Laradock. I'm very excited about it.

P.S. I think http://laradock.io/documentation/#adding-cron-jobs seems out of date; perhaps it means to say `vim workspace/crontab/laradock`?

**Comment by francislavoie** [comment]
>But I see OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

`php-worker` is an `alpine` based image which doesn't have `bash`. You should instead use `ash`, e.g. `docker-compose exec php-worker ash`

**Comment by ryancwalsh** [comment]
@francislavoie Thanks. Is http://laradock.io/documentation/#adding-cron-jobs out of date?

Assuming my site is already running (all my containers are already built and up) and I want to edit cron jobs, should I use `vim workspace/crontab/laradock` and add some lines like the following and then run `cd /apps/laradock && docker-compose restart php-worker`?  Or what are the steps? And where can I then go check and verify that the cron lines got written to the right place? (I would assume I'd need to look in a particular container and open `crontab -e` to see them there.) Thanks so much.

```
* * * * * laradock php /var/www/project1/artisan schedule:run >> /dev/null 2>&1
* * * * * laradock php /var/www/project2/release/artisan schedule:run >> /dev/null 2>&1
```

**Comment by francislavoie** [comment]
Yeah you'll need to restart the workers any time you change your code for jobs/scheduled tasks. Since it's run from PHP-CLI, the code is only loaded once when it first boots up, unlike PHP-FPM and such which loads your code on every request (with opcache in there to make that more efficient). It's a bit tedious, but it's what you have to do. You could write yourself a tool to watch for changes in the relevant code paths (with inotify for example) and restart the workers, if you want to lighten the development burden.

If you change the crontab, I think you need to rebuilt and re-run the workspace container for the changes to take effect. See the Dockerfile for workspace, it copies the crontab into the container at build time.

**Comment by ryancwalsh** [comment]
@francislavoie Thanks. Based on reading https://github.com/laradock/laradock/blob/v7.2.0/workspace/Dockerfile#L145, my latest guess was to run `cd /apps/laradock/ && docker-compose build workspace`, but that didn't seem to work either.

After rebuilding, I ran `cd /apps/laradock/ && docker-compose exec workspace bash` and then looked at both `crontab -e` and `vim /etc/cron.d/laradock`, and my cron jobs weren't there. 

I'm so confused. 

The last thing I can think to try is rebuilding with `--no-cache`. I don't know if that is the key.

**Comment by francislavoie** [comment]
After you rebuild you need to re-run it, e.g. `docker-compose up -d` for the rebuilt image to be recreated as a new container.

**Comment by ryancwalsh** [comment]
Ohhhh! You are so awesome, @francislavoie !! Thank you so much. That probably saved me days of frustration. I don't know whether I'd have learned that without you. Thanks. It worked.

**Comment by ryancwalsh** [comment]
@francislavoie I'm curious: where in the source code can I learn what `docker-compose restart php-worker` actually does? (Is it the [bottom of Dockerfile](https://github.com/laradock/laradock/blob/v7.2.0/php-worker/Dockerfile#L66)?)

One concern I have is that I'd _hope_ that jobs get "gracefully restarted" (as I read about in [Laravel docs here](https://laravel.com/docs/5.6/queues#queue-workers-and-deployment)) rather than anything being _abandoned_.

Another curiosity: is the `php-worker` container actually relevant to the cron jobs defined for `workspace` somehow? I haven't figured out how it relates.

Thanks **so much** for your help.

**Comment by francislavoie** [comment]
https://docs.docker.com/compose/reference/restart/ I think this is what you're looking for.

Unfortunately it's just the nature of how job workers work. It's one process that waits for jobs to be added to a queue, then runs them as they appear.

I think how laravel does it (I'm not at a PC right now to really check) is that the from schedule will actually spawn a job onto the queue, and php-worker runs it. You could experiment by turning off the worker container (docker-compose stop php-worker) and see if scheduled jobs still run.

**Comment by ryancwalsh** [comment]
@francislavoie Ok. I've always assumed that "cron jobs" were just processes run on a schedule defined in `crontab`. And "queue (or worker) jobs" were app-specific tasks that had been placed into either a Redis or database store and then executed by a long-running process (which in this case would be `php artisan queue`). I'll experiment. Thanks.

**Comment by francislavoie** [comment]
You're not wrong, I just think it's the case that laravel puts the jobs defined in the cron schedule on the queue. That might not be the case though.
