### ISSUE TITLE
Production: how to scale

### ISSUE THREAD

**Issue by andrewmclagan** [LaraDock/laradock#143]
How do people manage to scale the php-fpm and Nginx containers together? Say I want 3 containers of php-fpm running on two machines. I would also need an Nginx container for each of them?

**Comment by Mahmoudz** [comment]
@andrewmclagan I'm gonna close this, since it's been open for a long time and unfortunately no one answered it. If you were able to get help from anywhere and you found an asnwer, please share it with us I'd like to add it to the README (also feel free to submit a PR if you prefer), I think many people will benefit from this. thanks

**Comment by andrewmclagan** [comment]
We don't have individual container for nginx and php-fpm, we run supervisor, nginx and php-fpm in the same container. It makes your images much more portable and easier to orchestrate when having massively parallel deployments!

**Comment by andrewmclagan** [comment]
see https://github.com/andrewmclagan/aphex

**Comment by Mahmoudz** [comment]
@andrewmclagan thanks for the answer. I'm checking that..

**Comment by andrewmclagan** [comment]
@Mahmoudz The difference being, it seems that Laradock is mostly configured for development. IMO thats an oversight as a basic principal of Docker is immutable environments (same for production, staging and development) that way you 100% know what you get is dev is what you get in production.

The only questing then is what do you use to deploy and orchestrate your containers. Thats not in the scope of Laradock IMO. My suggestions would be:

Kubernetes, Rancher or Swarm. With Kubernetes as our preference.

**Comment by Mahmoudz** [comment]
@andrewmclagan you are absolutely right, LaraDock started mainly for development usage, however in the latest release we added a production version of the docker-compose.yml file to include the production configs.. as starting point to seriously support it on production with full documentations and solutions..

I won't be able to do that alone as I didn't yet had the chance to deploy large apps on production since this is outside the scope of my responsibility at the companies I work for where my major role is coding the apps and someone else deploys them...

That's why contributors like you may have great opinion regarding the containers orchestration and management.. I personally played with Kubernetes, Rancher and Swarm but I'm not confident enough to give answers in that area..

So your suggestions and maybe contributions are welcomed, and if you need to have discussions about any suggestions you can always discuss this on Gitter with around 80 awesome LaraDock users.

**Comment by andrewmclagan** [comment]
Thank you :) I will do that when I have time and thank you for your work!

**Comment by g0ld3lux** [comment]
Im also looking for a solution to scale easily using laradock...
i found rancher ... still looking and learning... Hope we can Make this Work out in the Near Future , hope others can share also their ideas and experience and make sugguestion How we can improve laradock ...
for scaling in production

**Comment by andrewmclagan** [comment]
Kuberbetes is the most mature IMO

**Comment by g0ld3lux** [comment]
How do you say its more mature , in the sense of?
