### ISSUE TITLE
variable APPLICATION not working

### ISSUE THREAD

**Issue by landah** [laradock/laradock#1473]
### Info:
- Docker version 17.05.0-ce
- Laradock commit 9c7bf5a
- System info Linux
- System info ubuntu/16.04: 

### Issue:
the application variable is not found in the env-example file and when you add the value, it does not produce the expected result
_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by mattharley** [comment]
It looks like this variable is now called `APP_CODE_PATH_HOST`. See commit a0c5ef75d2cc3462af537cb3a385ccb728e585c3

If you're happy to make a pull request to the documentation, the relevant file is: `laradock/DOCUMENTATION/content/getting-started/index.md`.

Otherwise I can probably put it together :)

**Comment by landah** [comment]
many, thanks to the new variable(APP_CODE_PATH_HOST) everything works properly.
