### ISSUE TITLE
Laradock questions ? :D

### ISSUE THREAD

**Issue by midascodebreaker** [LaraDock/laradock#160]
Hi ive been testing the whole docker and laradock for 2 days....
have face so many issue...

If someone can clear my mind to this question it would be awesome...

Scenario 1
# Default VM installed
# Container Installed
# One laravel Project 
# Laradock is a submodule

Question 1
Can i Use my containers to other project? or do i need to create a new VM then install set of containers again...

Question 2
I know i can On and Off Containers at will, but some Containers such as mariaDB and mysql cannot be interchangeable done in run time... you either need to choose one during installation....

My Question here is it is possible i can switch mariaDB and Mysql, Am i Missing Something?

Thanks a lot

**Comment by Mahmoudz** [comment]
Answer 1
You can container in many projects, without installing many VM's. So far you just need to do is `docker-compose stop` in your first project then `docker-compose up ...` in your next one. The only reason why you start and stop containers is because they might be exposing the same ports (if you use different ports example nginx 8080 and 8081, you don't even need to stop anything to use multiple projects), Check out #54 for more tricks.

Answer 2
I'm not sure I understand your case here, do you want to use MariaDB and MySql in the same project!! if that's the case you can and if you weren't able then change the ports and maybe the storage path. If you mean you want to use each for a project, then this is totally doable and you don't have to choose anything at run time, you just run whatever you want and any time you like.

Best
