### ISSUE TITLE
Npm install failed

### ISSUE THREAD

**Issue by gamevnlc** [laradock/laradock#1626]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 5016e88515a6ea2ee61153aa43b8af4c8e418b58
- System info (Mac, PC, Linux):  PC
- System info disto/version: windows 10 64bit

### Issue:
Can't install node sass on laradock
![image](https://user-images.githubusercontent.com/2215185/41805064-7774dfd6-76d4-11e8-8963-fef005cd1d62.png)

**Comment by atmar** [comment]
Exact same issue & environment here

**Comment by qnox81** [comment]
as workaround try downgrade node, f.e.
`nvm install 6.10.3`

**Comment by patrickcarlohickman** [comment]
One workaround is to use yarn. `yarn install` seems to work for me.

If you need npm instead of yarn, I was able to come up with a solution. I'm not sure if there is a better solution out there, but the one that works for me is to change the volume mount from CIFS 3.02 to CIFS 2.0.

I describe the process on an answer on StackOverflow: https://stackoverflow.com/questions/50981002/npm-install-on-laradock-not-working/52371510#52371510
