### ISSUE TITLE
Can't see my laravel app in the browser

### ISSUE THREAD

**Issue by davidavz** [LaraDock/laradock#166]
I have cloned the repo in an existing Laravel project and run `docker-compose up -d  nginx postgres`

On `http://localhost/` I have the default Nginx page
On `http://127.0.0.1/` I have 404 not found

I don't understand on which part I'm wrong.

I'm using Docker Beta on Windows 10
````
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true

````

**Comment by midascodebreaker** [comment]
i dont think there is a documentation about docker beta...

ive tried that approach before i but i revert back to docker toolbox...

simply because its on beta, and i cant even use my virtual box because of hyperv issue

coz i have existing project that runs on homestead...

but as i watch video , there is no more docker-machine ip command , coz it becames native

but i also learn that you can use docker.dev on windows and local.docker.dev on mac...

which is automatically generated for you when you do docker-machine start

try to view it on docker.dev

**Comment by Mahmoudz** [comment]
Check this maybe it helps! https://github.com/LaraDock/laradock#debugging

**Comment by davidavz** [comment]
I went back to Docker Toolbox like @midascodebreaker said and now it's all good.

I think i'm gonna wait for a "real" Docker for Windows before using it.

Thanks!
