### ISSUE TITLE
read the original laravel project .env file

### ISSUE THREAD

**Issue by broven** [laradock/laradock#1744]
In laradock directory, we have a .env file, It contains `MYSQL_DATABASE` and such things,besides, in our laravel project, we also have a .env file, It have some config variable, can we read from laravel .env file?
If I already can do that,,  please tell me how.
If can't, This is my request, If this look good to you, I or anyone will send the PR

**Comment by broven** [comment]
@vladyslavstartsev yeah, but laradock has some identical variables, such as `REDIS_HOST`  `DB_MYSQL` some thing like that, we have to maintain two of them, It seems a little bothering. (personal opinion)

**Comment by vladyslavstartsev** [comment]
@broven ok, I think it still bad idea, because people who use laradock, use it with `symfony`, `wordpress`, `magento`, `zend` and all other php frameworks and technologies that may not use `.env` files right now.
Also it was spited up by design.

But to solve your issue, there is a article on the docker docs https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option and for the laravel override the `LoadEnvironmentVariables` class

**Comment by broven** [comment]
@vladyslavstartsev thanks for your time! I'll close this issue.
