### ISSUE TITLE
The script hangs execution when it installs node.js

### ISSUE THREAD

**Issue by mdamaceno** [LaraDock/laradock#185]
I am trying to use Laradock, but I have a problem. After running ``docker-compose up -d nginx postgres php-fpm`` everything works fine until the step 22. Here is the output:

```
Step 22 : RUN . ~/.nvm/nvm.sh     && nvm install stable     && nvm use stable     && nvm alias stable     && npm install -g gulp bower
 ---> Running in bd88f2062c3b
Downloading https://nodejs.org/dist/v6.3.1/node-v6.3.1-linux-x64.tar.xz...
######################################################################## 100.0%
Now using node v6.3.1 (npm v3.10.3)
Creating default alias: default -> stable (-> v6.3.1)
Now using node v6.3.1 (npm v3.10.3)
stable -> 6.3 (-> v6.3.1) (default)
```

And nothing more happens... (cursor blinking)

Does anybody know how to fix that?

**Comment by Kauhat** [comment]
The `workspace` container seems to be being build even though you didn't specify it in the command above, and the problem seems to be happening there. I'm not sure why that is.

If you chop the below out from the `php-fpm` section of the `docker-compose.yml` you may be able to get nginx, postgres and php-fpm up without getting caught up in the workspace build.

```yaml
        links:
            - workspace
```

As for the actual issue, I'm not sure!

**Comment by computerfr33k** [comment]
I think the workspace link in the php-fpm section should be removed because it doesn't actually need to link to the workspace container for anything & the other way around.
