### ISSUE TITLE
[How to] Unable run node js script under php (www-data can't run external program)

### ISSUE THREAD

**Issue by Dolphin83** [laradock/laradock#1862]
### Info:
- Docker version (`$ docker --version`): Docker version 18.06.1-ce, build e68fc7a
- Laradock commit (`$ git rev-parse HEAD`): 436df887c9c606f83aa85516e8fd0e9ced7f5e32
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04.1 LTS

### Issue:

Unable run node js script under php

### Expected behavior:

 I should be able to run nodejs script under php

### Relevant Code:

I have installed nodejs in workspace container
```
w1@linux:~/docker/laradock$ docker-compose exec -u laradock workspace bash
laradock@004db963f293:/var/www$ node -v
v10.10.0
```
When i try to run same under php it fails
```
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

Route::get('/test', function () {
    $p = new Process('node -v');
    $p->run();
    if (!$p->isSuccessful()) {
        dump( new ProcessFailedException($p));
    } else {
        dump($p->getOutput());
    }
});
```

Output:
```
ProcessFailedException {#462 ▼
  -process: Process {#459 ▶}
  #message: """
    The command "node -v" failed.\n
    \n
    Exit Code: 127(Command not found)\n
    \n
    Working directory: /var/www/foo.local/public\n
    \n
    Output:\n
    ================\n
    \n
    \n
    Error Output:\n
    ================\n
    sh: 1: node: not found\n
    """
  #code: 0
  #file: "/var/www/foo.local/routes/web.php"
  #line: 44
  trace: {▶}
}
```

Let's find out which user performs code
```
Route::get('/test', function () {
    $p = new Process('whoami');
    $p->run();
    dump($p->getOutput());
});
```

Output:
```
"www-data\n"
```

So, user "www-data" does not know anything about installed node js

How i can fix it?

**Comment by vladyslavstartsev** [comment]
Hi! 

The problem is not in the user `www-data`.

See what happens - you have installed the node under the workspace container
and you're checking if it is there by `node -v`

but the requests are by other container called php-fpm. And in the php-fpm you don't have node installed


So you should install node there - see the example in dockerfile of workspace

https://github.com/laradock/laradock/blob/538b6aa0cd484c475c5c537a763e4e1fe330fcae/workspace/Dockerfile#L447-L468
