### ISSUE TITLE
Modifying the php-fpm configuration file workspace container does not take effect

### ISSUE THREAD

**Issue by sowork** [laradock/laradock#2056]

**Comment by sowork** [comment]
I did a build operation on php-fpm and wrkspace, but it still didn't work

**Comment by jasperf** [comment]
Did you also run it with `--no-cache`?

**Comment by sowork** [comment]
@jasperf Workspace containers and php-fpm containers do not share the same configuration file,Why does the workspace container have PHP installed separately,If I need to change the configuration under workspace bash via vim

**Comment by jasperf** [comment]
You did not add your docker-compose.yml here which would have helped. Workspace however does use PHP so you can run artisan commands from there which is one of the reasons we have Workspace. In your docker-compose.yml file you can configure it as well. PHP FPM container is used to process PHP for the application itself.

**Comment by sowork** [comment]
Maybe workspace and php-fpm share the same configuration file by default? Why not set the default?

**Comment by jasperf** [comment]
> Maybe workspace and php-fpm share the same configuration file by default? 
No, they don't in Laradock. But you are of course always able to roll your own setup.
> Why not set the default?
Because I guess a lot of people wanted flexibility and often want more in the workspace container than in the general purpose PHP FPM container. This because workspace is to manage ALL containers. Again, you can change it all.
