### ISSUE TITLE
Access app url

### ISSUE THREAD

**Issue by fridzema** [laradock/laradock#2065]
Hello,

Is there anybody here managed to connect to his own app url from the php-fpm or workspace container?

for example in one of those containers:
`curl https://app.test`

I have tried several things with expose and network aliases but can't get it to work.

**Comment by bumbummen99** [comment]
I have stumbled upon this while trying to get Laravel's built-in testing to work.

As far as i know you can reach the containers within the docker network with their container name, for example `http://nginx` does in fact work for me (`curl http://nginx -o public/curl-test.html`). Sadly i am still getting a 404 instead of an 200 when i do `$this->get('/')` in my tests .
