### ISSUE TITLE
xdebug not work

### ISSUE THREAD

**Issue by AndreiiP** [laradock/laradock#2112]
### Info:
- Docker version (`$ docker --version`): 17.05.0-ce, build 89658be
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Ubuntu
- System info disto/version: 18.04

// place a code sample here

xdebug ini
xdebug.remote_host=host.docker.internal
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM

xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.cli_color=1
xdebug.profiler_enable=0
xdebug.profiler_output_dir="~/xdebug/phpstorm/tmp/profiling"

xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1

settings php storm
http://i.imgur.com/9VKLXix.png

When I run the code, I get it
http://i.imgur.com/RmQ4wUn.png

A month ago, everything worked

**Comment by PricelessRabbit** [comment]
how do you use xdebug? are you listening for connections (via the green phone icon in xdebug) or are you debugging via the XDEBUG_SESSION_START parameter in the browser?
If you use the parameter it doesn't work anymore because of this modification 
https://github.com/laradock/laradock/pull/2100

I submit a PR to fix the issue

you have also to set remote_autostart=0, otherwise xdebug set the idekey attribute to "PHPSTORM" and not to the numeric value passed by XDEBUG_SESSION_START
