### ISSUE TITLE
Move build args to .env files

### ISSUE THREAD

**Issue by ikari7789** [LaraDock/laradock#215]
LaraDock could be much more modifiable if build args were moved to .env files rather than hard coded into the docker-composer.yml. The one downside to this though is that currently though Docker Compose will fail if the .env file is not found. This is a downside as typically the .env file would be gitignored so as to allow easy setting in an automated environment or per-user environment, so it may require some sort of a bootstrap script to create default .env files.

**Comment by Mahmoudz** [comment]
@ikari7789 yes you are right. We had the `.env` file before, but many users faced troubles with it. That's why I removed it and let it optional. I think users should treat the `docker-composer.yml` file as the config and customization file. However, I like the idea of having scripts to boot things up and prepare everything with couple simple commands.
