### ISSUE TITLE
How do I connect to a LAN machine service such as redis？

### ISSUE THREAD

**Issue by sowork** [laradock/laradock#2202]
### Info:
- Docker version 18.09.2, build 6247962
- Laradock commit: 63fc1fde44cc00aacb89511a441cb83685e8010c

- System info: windows PC 
- System info disto/version: Microsoft Windows [版本 10.0.18932.1000]

* I created two containers `php-fpm` and `nginx`
* My native IP is `192.168.1.12`
* I want the php-fpm container to connect to the `redis service` provided by one of the machines on the LAN
* php-fpm container IP is `172.25.0.4` 
* nginx container IP is  laradock_frontend `172.24.0.3`   laradock_backend `172.25.0.5`
* a LAN has two segments: `192.168.1.0/24`  and `192.168.10.0/24`, redis service on `192.168.10.0/24` network segment， my own machine is on the `192.168.1.0/24` network segment.

The document says that it can be configured as `REDIS_HOST=redis`

This is not suitable for me, I directly specify 192.168.10.244 display
Connection refused [tcp://192.168.10.244:6379]

what should I do?

**Comment by lanphan** [comment]
Unfortunately it's not supported on Windows.
Docker has macvlan network (https://docs.docker.com/network/macvlan/) so that you can use it to access other machines on your LAN network. However, macvlan is not supported on Docker Desktop for Windows (https://docs.docker.com/network/network-tutorial-macvlan/)
