### ISSUE TITLE
php-worker does not work with MSSQL

### ISSUE THREAD

**Issue by aiaiwuai** [laradock/laradock#2271]
### Info:
- Docker version Docker version 19.03.2, build 6a30dfc: 
- Laradock commit cb910c590e00cee77ebbf75867aae0c7d0199119: 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:
When run some schedules which use mssql  leads error. Find php-fpm and workspace have the install command but php-worker doesn't.

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by lanphan** [comment]
As I remember, php-worker is based on Alpine, and workspace / php-fpm based on Debian.
Due to Alpine doesn't use official C compiler like other Linux distributions, Microsoft doesn't support Sql server driver on Alpine, but you can use generic sql driver on Linux.
However, when I tried that, I found that generic sql driver is not good enough to use (for ex, not automatically add prefix N'' for nvarchar type). I did create another php-worker image based on Debian, let I create PR to share with you soon.

**Comment by AndreFigueredo-Multilaser** [comment]
@pavinthan Can you post as you did?

**Comment by AndreFigueredo-Multilaser** [comment]
> As I remember, php-worker is based on Alpine, and workspace / php-fpm based on Debian.
> Due to Alpine doesn't use official C compiler like other Linux distributions, Microsoft doesn't support Sql server driver on Alpine, but you can use generic sql driver on Linux.
> However, when I tried that, I found that generic sql driver is not good enough to use (for ex, not automatically add prefix N'' for nvarchar type). I did create another php-worker image based on Debian, let I create PR to share with you soon.

Can you post as you did?
