### ISSUE TITLE
PHP 7.4 and laravel horizon

### ISSUE THREAD

**Issue by lionslair** [laradock/laradock#2407]
### Info:
- Docker version (`$ docker --version`): Docker version 19.03.5, build 633a0ea838
- Laradock commit (`$ git rev-parse HEAD`): https://bitbucket.org/lionslair/laradock/src/master/
- System info (Mac, PC, Linux): Ubuntu 18.04 LTS
- System info disto/version: 

### Issue:
Using php 7.4 in .env I get the following output 
checking for oniguruma... no
configure: error: Package requirements (oniguruma) were not met:

Package 'oniguruma', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
ERROR: Service 'laravel-horizon' failed to build: The command '/bin/sh -c docker-php-ext-install mysqli mbstring pdo pdo_mysql tokenizer xml pcntl exif' returned a non-zero code: 1
_____

### Expected behavior:
laravel-horizon compiles with php 7.4

### Reproduce:
Clone the above repository and do docker-compose up with .env PHP_VERSION=7.4
_____

### Relevant Code:

```
checking for oniguruma... no
configure: error: Package requirements (oniguruma) were not met:

Package 'oniguruma', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
ERROR: Service 'laravel-horizon' failed to build: The command '/bin/sh -c docker-php-ext-install mysqli mbstring pdo pdo_mysql tokenizer xml pcntl exif' returned a non-zero code: 1
```

**Comment by zoulux** [comment]
I have repaired it
`RUN docker-php-ext-install mysqli pdo pdo_mysql tokenizer xml pcntl
`
delete mbstring

**Comment by lionslair** [comment]
Your fix seems to solve that original issue but then I get issues about 
configure: error: unrecognized options: --with-libzip

and similar with other parts. I feel like maybe other containers or options are not ready for php 7.4 yet. Do not get the issues on 7.3

**Comment by zoulux** [comment]
@lionslair yes，you are right。It not ready for php 7.4 yet。

**Comment by aj-norman** [comment]
I had the issue, and I provided a fix in #2414, its for the php worker, but may work for laravel horizon

**Comment by kadekjayak** [comment]
i also get those error message when trying to build `php-worker` with PHP 7.4

removing mbstring on Dockerfile like @zoulux suggest has fix the problem :D

**Comment by lorisleiva** [comment]
Hi there 👋

I was also struggling to upgrade my [Laravel Dockerfile](https://github.com/lorisleiva/laravel-docker) from 7.3 to 7.4 and I was having the exact same error messages.

1. First, I got the error `configure: error: unrecognized options: --with-libzip` which I fixed by **removing the following line** since [according to this](https://stackoverflow.com/a/48700777/11440277), it is now re-bundled by PHP >= 7.3.

```Dockerfile
RUN docker-php-ext-configure zip --with-libzip
```

2. Next, I got the error `configure: error: Package requirements (oniguruma) were not met`. I fixed that one by **removing the installation of `mbstring`** since [according to this](https://stackoverflow.com/a/59253249/11440277), it is already installed and configured by the PHP image I was using. An alternative to that one is to install the `libonig-dev` library to fix the dependency problem.

I hope this helps 🍀
