### ISSUE TITLE
I've no idea why use 82 as uid for www-data

### ISSUE THREAD

**Issue by mcwz** [laradock/laradock#2536]
https://github.com/laradock/laradock/blob/123e52e563fb507a7089952ff227df4c5e0daee6/nginx/Dockerfile#L25

But in nginx container , /var/www is belong to uid 1000.
When I open app.test ,it shows 404 .

**Comment by waiyan13** [comment]
This. I was racking my brain for hours why my source folder is owned by 1000.

I wanted to use separate `app.conf` instead of `default.conf` inside `nginx/sites/`. If I used this way, I can't access the `index.html` I put inside the source folder. Putting it inside `public` folder didn't help either.

The only way this works is to use `default.conf` and add your source folder explicitly. I want to know the reason why I can't use custom site configuration.

**Comment by ErnestStaug** [comment]
I am having alot of issues with UID's and permissions... For example log file get's set by different user each time some containers run as a root some of them as laradock user... And not all of the containers can write logs.

**Comment by kenng** [comment]
@mcwz @ErnestStaug 

spent some time to check on this, for Nginx with php-fpm, it's the php-fpm container that create the file in the mounted volume.

Therefore you should check in `php-fpm` container the user `www-data` and make sure it has access to the mounted volume or permission denied will happen. For mine case, new file created initially was set with 1000:33, which resulted no permission to write (since allowed group id is 82 on mounted volume)

try add the group  `82` to the `www-data` user in `php-fpm` container.
