### ISSUE TITLE
workspace swoole --enable-openssl

### ISSUE THREAD

**Issue by jwwb681232** [laradock/laradock#2637]
### Description:
```shell
ERROR   php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught Swoole\Coroutine\Http\Client\Exception: you must configure with `--enable-openssl` to support ssl connection when compiling Swoole
```

**Comment by 100phel** [comment]
I have the same error. Can you reopen this?

**Comment by 100phel** [comment]
Meanwhile, using a little hack: instead of plain `pecl install swoole;` in the workspace Dockerfile I use
`printf "yes\nyes\nyes\nyes\n" | pecl install swoole;`
It answers 'yes' to the installation prompts that are 'no' by default:

enable sockets supports? [no] :
enable openssl support? [no] :
enable http2 support? [no] :
enable mysqlnd support? [no] 

And the resulting configuration looks like this: `running: /tmp/pear/temp/swoole/configure --with-php-config=/usr/bin/php-config --enable-sockets=yes --enable-openssl=yes --enable-http2=yes --enable-mysqlnd=yes`

**Comment by Prince-254** [comment]
> Meanwhile, using a little hack: instead of plain `pecl install swoole;` in the workspace Dockerfile I use
> `printf "yes\nyes\nyes\nyes\n" | pecl install swoole;`
> It answers 'yes' to the installation prompts that are 'no' by default:
> 
> enable sockets supports? [no] :
> enable openssl support? [no] :
> enable http2 support? [no] :
> enable mysqlnd support? [no]
> 
> And the resulting configuration looks like this: `running: /tmp/pear/temp/swoole/configure --with-php-config=/usr/bin/php-config --enable-sockets=yes --enable-openssl=yes --enable-http2=yes --enable-mysqlnd=yes`
> 
> Or, if you need just openssl support, then you can use:
> `printf "no\nyes\nno\nno\n" | pecl install swoole;`

Wooow you saved my skin pal thanks
