### ISSUE TITLE
php-fpm faketime library

### ISSUE THREAD

**Issue by j1yak** [laradock/laradock#2754]
### Description:
faketime library only works with php 7.1. with higher versions. the php-fpm doesn't response 

I can't find any log showing the error

### Steps to reproduce the issue:
PHP_FPM_INSTALL_FAKETIME=true
PHP_FPM_FAKETIME=2021-01-01 19:03:00

**Comment by j1yak** [comment]
@4c0n could you review it?

**Comment by 4c0n** [comment]
Sorry haven't worked on or used laradock and libfaketime in years. If I
remember correctly it would kind of hijack the system clock and present a
different time to php.
No clue why it's not working anymore, maybe something changed with
libfaketime or with how php reads the time from the system clock?
Just to be clear I have no intention of looking into this, so it's probably
best if you try to figure it out by yourself or find someone else to help
you out. 🙂

**Comment by ifnull** [comment]
I was having a similar issue with a [Lando](https://docs.lando.dev/) setup for a WordPress application in a Docker container running Apache. Everything worked fine until the application tried connecting to a database in another container. This manifested as an error like ` mysqli_real_connect(): (HY000/2002): Connection refused in ...` and `Fatal error: Maximum execution time of 90+2 seconds exceeded (terminated) in ...` depending on which plugins were enabled. Using the `@` prefix for a start-at timestamp resolved my issue. 

As pointed out by @mgurjanov-jobiqo, the solution is to prefix the timestamp with an `@`. The prefix tells FAKETIME to start at that timestamp instead of being frozen at that timestamp. Something in the PHP application is waiting on the time to change but without the `@` the time never changes. Someone pointed to `uniqid()` being the source of the issue in another thread. There may be similar functions such as `sleep()` that could cause this as well.
