### ISSUE TITLE
Not working ImageMagick in php-fpm

### ISSUE THREAD

**Issue by Windd01** [laradock/laradock#2856]
Is your feature request related to a problem? Please describe.
Not working ImageMagick in php-fpm

Describe the solution you'd like
Change this piece of code in php-fpm/Dockerfile

ARG INSTALL_IMAGEMAGICK=false

RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick \
;fi
to this

ARG INSTALL_IMAGEMAGICK=false

RUN apt-get update

RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick \
;fi

**Comment by bestlong** [comment]
#2862

**Comment by vlauciani** [comment]
> #2862

This PR install correctly the `ImageMagick` into `php-fpm` with `php8.0` but do not solve the problem mentioned above and here: https://github.com/laradock/laradock/issues/2865

to solve the problem, check the PR:
- https://github.com/laradock/laradock/pull/2866

**Comment by bestlong** [comment]
try `docker-compose build --no-cache --pull php-fpm`

**Comment by morales2k** [comment]
I've attempted to install it for php 7.3 and even though I set the .env to true to install imagemagick in the workspace container, it seems to fail to install the `libmagickwand-dev` properly.

After the install, if I review the dockerfile commands, and prepend an `apt-get update` I am able to properly install the required packages.

I am yet to test adding the update to the dockerfile right there on the imagemagick install step, because it seems it would not be required or needed, but for some reason, if you login as root into the container, and try to install libmagickwand-dev without updating first, it will fail.
