### ISSUE TITLE
504 Gateway Time-out (nginx)

### ISSUE THREAD

**Issue by armandojose009** [LaraDock/laradock#304]
hi , how can run nginx for more time ??

**Comment by Mahmoudz** [comment]
@armandojose009 could you be more specific? what is the problem or the question. Thanks.

**Comment by Mahmoudz** [comment]
I'll close this for now, feel free to open it again if you need. Best,

**Comment by baddwin** [comment]
Hi @Mahmoudz , I'd like to reopen this issue, as I got another 504 error as well.
I have a project that require Oracle database, so I build `php-fpm` version 5.6 and inside its workspace, I installed `oci8` extension by `docker-php-ext-install oci8`. The installation has completely done, and no error. Then I restart the `php-fpm` container in order to `oci8` extension is loaded. But I just got 504 error instead. Please help.

**Comment by pablorsk** [comment]
## Solution:

Step 1: Add `fastcgi_read_timeout 480;` to your `nginx/sites/your_config_file.conf`. You obtain something like this:
```conf
    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 480;
        include fastcgi_params;
    }
```

Step 2: Add this to `php-fpm/laravel.ini`

```ini
max_execution_time=480
default_socket_timeout=3600
request_terminate_timeout=480
```

Step 3: rebuild

```bash
sudo docker-composer up --build nginx mysql
```

**Comment by sbarbosa115** [comment]
It works for me, thanks.

**Comment by christiangoudreau** [comment]
I'm also running in that issue... The weird thing is that I have some route that works... and other that doesn't
