### ISSUE TITLE
Problem with rabbitmq

### ISSUE THREAD

**Issue by pvkhanh1708** [laradock/laradock#3096]
### Error:
When I run this command: docker-compose build nginx mongo redis rabbitmq php-worker
I get error below

ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.rabbitmq.ports contains an invalid type, it should be a number, or an object

It's RabbitMQ config in docker-compose.yml
### RabbitMQ #############################################
    rabbitmq:
      build: ./rabbitmq
      ports:
        - "${RABBITMQ_NODE_HOST_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
        - "${RABBITMQ_WEB_STOMP_HOST_PORT}:15674"
      privileged: true
      hostname: laradock-rabbitmq
      volumes:
        - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        - ./rabbitmq/management_agent.disable_metrics_collector.conf:/etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf
      depends_on:
        - php-fpm
      networks:
        - backend

Please help me!

**Comment by selfline** [comment]
I have this problem too.
`$ docker-compose up -d workspace nginx phpmyadmin
The WORKSPACE_INSTALL_TRADER variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_TRADER variable is not set. Defaulting to a blank string.
The PHP_WORKER_INSTALL_MSSQL variable is not set. Defaulting to a blank string.
The MONGO_USERNAME variable is not set. Defaulting to a blank string.
The MONGO_PASSWORD variable is not set. Defaulting to a blank string.
The RABBITMQ_WEB_STOMP_HOST_PORT variable is not set. Defaulting to a blank string.
The Compose file '.\docker-compose.yml' is invalid because:
services.rabbitmq.ports contains an invalid type, it should be a number, or an object`

**Comment by simonbuehler** [comment]
check your env file, i guess some entries from .env.example are missing

**Comment by pndx** [comment]
same problem when i try to rebuild
