### ISSUE TITLE
Cannot build PHP 8.0

### ISSUE THREAD

**Issue by gecas** [laradock/laradock#3133]
### Description:
I have cloned clean version of Laradock and cannot build php 8.0

### Expected Behavior:
Build and serve php 8

### Context information:

**Output of `git rev-parse HEAD`**
![image](https://user-images.githubusercontent.com/6697571/150791440-7e01afd8-2199-4765-a991-b06d1328650e.png)
 php-xml extension is present
```

**System info: Mac, Windows or Linux. Include which disto/version**

Ubutnu 20.04

### Steps to reproduce the issue:
<!--- How can we reproduce the issue? -->

1. git clone laradock
2. sudo docker-compose up -d --build workspace nginx redis php-fpm docker-in-docker

**Comment by Stereotip42** [comment]
+1

**Comment by catPixel** [comment]
+1

I have the same problem.

**Comment by es-makarevich** [comment]
+1

**Comment by SpurIT** [comment]
+1

**Comment by AlexRutkovskiy** [comment]
+1

**Comment by amiltonsoares** [comment]
+1

**Comment by zhernosekim** [comment]
Text of error for SEO:
"xml extension is not found"

**Comment by jdefelice** [comment]
Something was changed over the weekend.

Using this image works `laradock/workspace:20220115-8.0` from https://hub.docker.com/r/laradock/workspace/tags 

The` lastest-8.0` and `master-8.0` install php version 8.1.1 for some reason.

**Comment by grigoriy-ivanov** [comment]
+1

**Comment by Midlou** [comment]
+1

**Comment by Mauricio-L-Souza** [comment]
+1

**Comment by twohotko** [comment]
> Something was changed over the weekend.
> 
> I'm not sure if this is related but using the workspace `laradock/workspace:lastest-8.0` with bitbucket pipelines. Composer install fails because the php version is set to 8.1.1 and not version 8.0. When I revert back to a previous version `laradock/workspace:20220115-8.0` everything works as expected.

Followed this changed from 
WORKSPACE_BASE_IMAGE_TAG_PREFIX=latest to WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115

Build Success

**Comment by gecas** [comment]
> Something was changed over the weekend.
> 
> I'm not sure if this is related but using the workspace `laradock/workspace:lastest-8.0` with bitbucket pipelines. Composer install fails because the php version is set to 8.1.1 and not version 8.0. When I revert back to a previous version `laradock/workspace:20220115-8.0` everything works as expected.

yeah, probably, because I have another machine working with PHP 8 and laradock but it was setup earlier, thanks for quick response and taking a look into this, highly appreciate

**Comment by gecas** [comment]
> > Something was changed over the weekend.
> > I'm not sure if this is related but using the workspace `laradock/workspace:lastest-8.0` with bitbucket pipelines. Composer install fails because the php version is set to 8.1.1 and not version 8.0. When I revert back to a previous version `laradock/workspace:20220115-8.0` everything works as expected.
> 
> Followed this changed from WORKSPACE_BASE_IMAGE_TAG_PREFIX=latest to WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115
> 
> Build Success

It works with PHP 8 for you?

**Comment by jdefelice** [comment]
Laravel Sail has had a similar problem. https://github.com/laravel/sail/pull/316

**Comment by andreypopov** [comment]
> > Something was changed over the weekend.
> > I'm not sure if this is related but using the workspace `laradock/workspace:lastest-8.0` with bitbucket pipelines. Composer install fails because the php version is set to 8.1.1 and not version 8.0. When I revert back to a previous version `laradock/workspace:20220115-8.0` everything works as expected.
> 
> Followed this changed from WORKSPACE_BASE_IMAGE_TAG_PREFIX=latest to WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115
> 
> Build Success

+1 thanks!

**Comment by Rijoedi** [comment]
> > > Something was changed over the weekend.
> > > I'm not sure if this is related but using the workspace `laradock/workspace:lastest-8.0` with bitbucket pipelines. Composer install fails because the php version is set to 8.1.1 and not version 8.0. When I revert back to a previous version `laradock/workspace:20220115-8.0` everything works as expected.
> > 
> > 
> > Followed this changed from WORKSPACE_BASE_IMAGE_TAG_PREFIX=latest to WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115
> > Build Success
> 
> It works with PHP 8 for you?

Worked here using PHP 8.0 on env file.

**Comment by datsiuk7** [comment]
+1 thanks!

**Comment by turb0bur** [comment]
@twohotko 
+1
changing WORKSPACE_BASE_IMAGE_TAG_PREFIX from latest to the specific one works like a charm))
Thanks!
God will bless you guy!

**Comment by simonbuehler** [comment]
please merge, fixed the `XML Extension not found` error

**Comment by andreypopov** [comment]
Now I get 
` => ERROR [laradock_workspace  95/107] RUN set -xe; php -v | head -n 1 | grep -q "PHP 8.0."  `

**Comment by dhtmdgkr123** [comment]
+1

**Comment by fdjkgh580** [comment]
+1

**Comment by weecorp** [comment]
OMG... been stuck on this googling for hours... this worked for me too. Thank you.

**Comment by lionslair** [comment]
Had the same issue as above. Locking the tag as suggested worked. But due to other changes in my dockerfile I also needed to set PHP 8.0 at the of the docker file because something along the way had still added php8.1.1 as the default to use on the cli.

I see the image latest was republished on the weekend. Haven't checked if this fixed the issues though

**Comment by etal0n** [comment]
> I see the image latest was republished on the weekend. Haven't checked if this fixed the issues though

Still not working.

**Comment by ewatch** [comment]
Using the above and solving the connection timeout for the node installation made the workspace being build properly for me today meaning:
```
WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115
```

and

```
WORKSPACE_NODE_VERSION=lts/fermium
```

see also #2843

**Comment by svenfahrni** [comment]
Changing the BASE_IMAGE_TAG_PREFIX got me the following error: 

`
=> ERROR [100/108] RUN set -xe; php -v | head -n 1 | grep -q "PHP 8.0."  0.4s
`

**Comment by andreypopov** [comment]
> @andreypaa @dhtmdgkr123
> 
> Changing the BASE_IMAGE_TAG_PREFIX got me the following error:
> 
> `=> ERROR [100/108] RUN set -xe; php -v | head -n 1 | grep -q "PHP 8.0." 0.4s`
> 
> The build succeeded by removing the following line of the Dockerfile:
> 
> https://github.com/laradock/laradock/blob/01ab8c7d1e12f7ed7d6c80651f396ce5661d2583/workspace/Dockerfile#L1542
> 
> However, after running the command manually, it seems like it installed the wrong version of php... PHP 8.1.2 (cli) (built: Jan 24 2022 10:42:33) (NTS)

the same, php 8.1 in workspace....

**Comment by rkafui** [comment]
> 

This worked for me, thank you

**Comment by elliotmassen** [comment]
I don't think that this issue is completely resolved by either of the previous suggestions (changing the base image tax prefix, and commenting out the PHP version check). Both suggestions leave the workspace image with PHP 8.1 installed even if `LARADOCK_PHP_VERSION` is set to `8.0`. Myself and @patshone-gsl took a look into the problem and arrived at the following solution.

**Solution**: add `RUN update-alternatives --set php /usr/bin/php${LARADOCK_PHP_VERSION}` after the `USER root` statement in `workspace/Dockerfile`

---

It seems even [the latest Laradock CI action run for PHP 8.0 workspace](https://github.com/laradock/laradock/runs/5080664378) has the same issue as described here. I pulled [laradock/workspace](https://github.com/laradock/workspace) locally and built the workspace PHP 8.0 base image, and found that both PHP 8.0 & PHP 8.1 are installed. `php` was incorrectly symlinked to PHP 8.1, rather than PHP 8.0.

On further investigation, the workspace image seems to install PHP from the `ppa:ondrej/php` [archive](https://launchpad.net/~ondrej/+archive/ubuntu/php). There is an issue raised in the bug tracker there (https://github.com/oerdnj/deb.sury.org/issues/1711) which describes a similar problem related to the undesired installation of PHP 8.1 instead of PHP 8.0. From the comments on that issue, and that repository's [FAQ](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#why-is-phpdefaultversion-cli-always-installed), it seems that PHP 8.1 is installed because it is (indirectly) a recommended package of one of the dependencies. PHP 8.1 then takes precedent as the virtual `php` package over PHP 8.0.

Therefore the `update-alternatives` command (described above) will ensure that the correct PHP version is used when `php` is called in the image. I'll raise a PR against the workspace repository in case this solution is desirable in the base image.

**Comment by lionslair** [comment]
> **Solution**: add `RUN update-alternatives --set php /usr/bin/php${LARADOCK_PHP_VERSION}` after the `USER root` statement in `workspace/Dockerfile`

I am doing that but at the end

**Comment by deivyrene** [comment]
> RUN update-alternatives --set php /usr/bin/php${LARADOCK_PHP_VERSION}

This worked for me with `php-5.6`

Thank's @elliotmassen

**Comment by ubrette** [comment]
https://cyrildewit.github.io/2020/04/19/how-to-change-the-PHP-version-in-Laradock/

**Comment by MrGUOFU** [comment]
> 

good!!! it works !

**Comment by Zykhatslover** [comment]
Worked like a charm with @ubrette link ! 

Too bad we can't just have multiple PHP versions in the same container and switch easily but it'll do as is !

Thank's :-)
