### ISSUE TITLE
Idea: Share SSH Config with Docker

### ISSUE THREAD

**Issue by edmundluong** [laradock/laradock#359]
Hi,

Suppose in your composer.json file you want to specify a private repository that you want to use as a dependency in your project:

composer.json

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "git@bitbucket.org:example/my-private-repo.git"
        }
    ],
    "require": {
        "example/my-private-repo": "1.0.*"
    }
}
```

When you run `composer update` to retrieve this new dependency, it uses your SSH key in `~/.ssh/id_rsa.pub` to pull the private repo. 

This works fine on the local system, however, trying to run `composer update` within the docker instance does not work since it does not have the same SSH config as the local system.

It looks like this can be achieved by copying your local SSH key to the instance: http://stackoverflow.com/questions/18136389/using-ssh-keys-inside-docker-container 

Perhaps there could be an option in the config for the workspace container in Laradock to pass in your SSH key so you can take advantage of private repos in Composer? Let me know your thoughts!

**Comment by philtrep** [comment]
@edmundluong Good idea. I would see this as an optional build argument to the Docker Compose file. If you feel like making a PR go ahead :)

**Comment by Mahmoudz** [comment]
@edmundluong I agree with @philtrep it's a good idea. I encourage you to make the PR as Phil suggested. Cheers.

**Comment by philtrep** [comment]
@edmundluong Any progress on this? If you aren't actively working on it we'll add an `Help Wanted` tag since this looks like a desired feature.

**Comment by scoutman57** [comment]
This is a much needed feature

**Comment by edmundluong** [comment]
@philtrep Unfortunately I am unable to work on this at point in time so perhaps it's best to add the tag. Thanks!

**Comment by philtrep** [comment]
@edmundluong Sounds good, thank you for the fast reply and the idea.

We are now looking for people willing to implement this.

**Comment by michaeljhopkins** [comment]
Unable to implement. But very interested in having this available

**Comment by dirkgroenen** [comment]
Just started using laradock as replacement for homestead and really needed this one. Tried to get it implemented but I couldn't find a nice way to get our host's pub key into the image, unless you would want to paste your key's content as `ARG`, copy it to the build directory or something like that.

Solution I've been using for now is to mount the public key in the container:
```
[..]
        volumes:
            - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
[..]
```

This doesn't feel like a proper solution compared to how other features are working, since it doesn't allow you to turn it on or off as an option. Reason for this post: in case anyone stumbles on this topic; this at leas does the job. 

Ps: if you do see this as a proper integration I'm happy to open a PR for it.

**Comment by dirkgroenen** [comment]
Just started using laradock as replacement for homestead and really needed this one. Tried to get it implemented but I couldn't find a nice way to get our host's pub key into the image, unless you would want to paste your key's content as `ARG`, copy it to the build directory or something like that.

Solution I've been using for now is to mount the hosts .ssh dir in the container:
```
[..]
        volumes:
            - ~/.ssh:/root/.ssh
[..]
```

This doesn't feel like a proper solution compared to how other features are working, since it doesn't allow you to turn it on or off as an option. Reason for this post: in case anyone stumbles on this topic; this at leas does the job. 

Ps: if you do see this as a proper integration I'm happy to open a PR for it.

**Comment by netojose** [comment]
If is the ideal, I don't know @dirkgroenen , but solved my problem. Thanks!

**Comment by NioTeX** [comment]
Why has this been closed? I think this would be a great feature, and even though a developer has been not found to implement it, closing it doesn't feel like the best solution.

**Comment by nicklee1990** [comment]
I will try and submit a PR for this at some point this week

**Comment by jelleroorda** [comment]
Not sure when this feature was added, but nowadays it's possible to copy a SSH key to your workspace container. You can do this as follows;

1. Generate new SSH keys for your docker container, then add these SSH keys in Github/Bitbucket etc.
2. Edit your `.env` file, set `WORKSPACE_INSTALL_WORKSPACE_SSH=true`
3. Overwrite the existing ssh key files in the `laradock/workspace` directory. First remove existing keys:
`rm insecure_id_rsa && rm insecure_id_rsa.pub && rm insecure_id_rsa.ppk`. Then move your newly generated keys there `mv ~/.ssh/your_new_key ./workspace/insecure_id_rsa && mv ~/.ssh/your_new_key.pub ./workspace/insecure_id_rsa.pub`.
4. Remove current build: `docker-compose down`
5. Rebuild workspace container `docker-compose build --no-cache workspace`
6. 🚀 Launch the build `docker-compose up -d <...container>`
