### ISSUE TITLE
Problems access localhost (Chrome: ERR_EMPTY_RESPONSE)

### ISSUE THREAD

**Issue by felipefreitasweb** [LaraDock/laradock#374]
Hello!

Recently formatted my macbook, and installed docker (see 1.12.1) and git to run laradock.
But when access http: // localhost I get the message ERR_EMPTY_RESPONSE (Google Chrome) 

My project directory:
<img width="455" alt="captura de tela 2016-10-17 as 00 21 25" src="https://cloud.githubusercontent.com/assets/9322269/19423589/8a7afa42-9400-11e6-9bdb-4aa24d842aae.png">

My docker status:
<img width="1213" alt="captura de tela 2016-10-17 as 00 22 03" src="https://cloud.githubusercontent.com/assets/9322269/19423605/bcc63692-9400-11e6-9ddf-e2c711510f5b.png">

My hosts:
<img width="441" alt="captura de tela 2016-10-17 as 00 22 47" src="https://cloud.githubusercontent.com/assets/9322269/19423608/ccb1f2bc-9400-11e6-872a-eaf1550b64ae.png">

Chrome Message:
<img width="975" alt="captura de tela 2016-10-17 as 00 22 31" src="https://cloud.githubusercontent.com/assets/9322269/19423614/d8958c88-9400-11e6-96b8-664a7cf766b0.png">

Anyone have any idea what can be?

** sorry for my English :(

Thanks!

**Comment by felipefreitasweb** [comment]
UPDATE *****

The problem happens only with apache2, with nginx everything worked.

**Comment by calebfavor** [comment]
@felipefreitasweb - I had the same problem, the issue is apache is not starting properly due to a config issue (if you check the logs you should see that apache is restarting over and over)

Extra quotes were added to the apache base image ([https://github.com/webdevops/Dockerfile/commit/b99e229698efa50abb922fefd40cb5a122f1c203](url)) so you need to edit 2 files in your laradock folder.

docker-compose.yml: under Apache Server Container change 
**PHP_SOCKET="php-fpm:9000"**
to
**PHP_SOCKET=php-fpm:9000**

Then in the apache/Dockerfile change:
**ARG PHP_SOCKET="php-fpm:9000"**
to
**ARG PHP_SOCKET=$PHP_SOCKET**

Cheers!

**Comment by philtrep** [comment]
@calebfavor Shouldn't `ARG PHP_SOCKET="php-fpm:9000"` be changed to `ARG PHP_SOCKET=php-fpm:9000` instead?

**Comment by calebfavor** [comment]
@philtrep Possibly, I am not sure what the correct way is. However I don't see a reason not to reference the composer file directly.

**Comment by felipefreitasweb** [comment]
It worked! 
@calebfavor  Worked perfectly! thanks! :D 

I followed exactly what I said, look:

**apache2/dockerfile**
<img width="261" alt="captura de tela 2016-10-17 as 19 58 00" src="https://cloud.githubusercontent.com/assets/9322269/19457286/625d70cc-94a4-11e6-9b5c-af87f47fafb2.png">

**docker-compose-yml**
<img width="381" alt="captura de tela 2016-10-17 as 19 57 42" src="https://cloud.githubusercontent.com/assets/9322269/19457312/7e710eae-94a4-11e6-8b55-32d57dc4c29c.png">

And run: **docker-compose build apache2**

Thank you very much!

**Comment by calebfavor** [comment]
@felipefreitasweb No worries! As @philtrep mentioned, the arg should indeed be changed to **ARG PHP_SOCKET=php-fpm:9000** rather than using the environment variable.

**Comment by philtrep** [comment]
#375 should fix this issue
