### ISSUE TITLE
Can't ADD things to /var/www/laravel/ in the workspace

### ISSUE THREAD

**Issue by markdev** [LaraDock/laradock#377]
I need to dynamically `ADD` a few files to the workspace container.  For some reason, I can `ADD` a file from Dockerfile to certain directories, but not others.

Near the bottom of workspace/Dockerfile (around "Final Touch"), I've added the following:
```bash
#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#

COPY ./FOO.txt /var/www/laravel/
ADD ./FOO.txt /usr/local/etc/
```

When I do `docker-compose up -d` and go into the container, I see FOO.txt in `/usr/local/etc/`, but not in `/var/www/laravel/`.

Is `/var/www/laravel/` somehow locked?  What is the best way to `ADD` files to this directory?

**Comment by philtrep** [comment]
@markdev The directory `/var/www/laravel/` is where the volume for your laravel app gets mounted by docker-compose. Since docker-compose mounts happen after building the containers, your FOO.txt is probably getting overwritten.

I suggest adding your files in the same directory as your laravel project on your host machine, you'll see the file along with the rest of your project in `/var/www/laravel/` in `workspace`.

Let me know if this fixes your problem :)

**Comment by markdev** [comment]
@philtrep Thanks for the prompt response!

I can and do do this now; currently I am running a shell script to `cp` the `.env` and `docker-compose.yml` files.  But that is a bad practice; it relies on the environment outside of the containers.  I'd like to be able to do this within the docker ecosystem, like with a `RUN` command or a `command:` in the .yml file.  All these attempts run into the same problem.

Is there a way to run this in docker after the volumes are mounted?

**Comment by philtrep** [comment]
@markdev Glad to hear it.

I am closing this issue since your problem is resolved.

About your follow-up, I am not exactly sure what it is you are trying to do. _Everything_ in your project folder should already be available from within your containers.

I suggest going over to [Gitter](https://gitter.im/LaraDock/laradock) for project specific questions, the other contributors might be able to give you better answers.
