### ISSUE TITLE
Symfony AsseticBundle problem. How run node command via php

### ISSUE THREAD

**Issue by sashaaro** [laradock/laradock#398]
Hi. I use symfony and  [Assetic Bundle](https://github.com/symfony/assetic-bundle). (it use [kriswallsmith/assetic](https://github.com/kriswallsmith/assetic)). 
It don't work and throw exception
`Path to node executable could not be resolved  in /var/www/ho/vendor/kriswallsmith/assetic/src/Assetic/Filter/UglifyCssFilter.php line 111`
 Seems php execute nodejs.
[In bundle settings I can set nodejs path file](https://symfony.com/doc/current/assetic/uglifyjs.html#configure-the-node-binary) . But I don't know where it is and what I need do for fix it

**Comment by manshoor** [comment]
@sashaaro have you enabled Node in workspace container?

if you do, than go to your workspace container and try this

`node -v` to see the version of installed node

`npm install -g uglifycss uglify-js` Install uglify css and js using npm

`ls /usr/local/bin/ | grep 'ugli'` use this command to see if files exists 

If you find both of file using the above command then go to your Symfony dir and try this command

`php app/console cache:clear`

`php app/console assetic:dump`

**Comment by sashaaro** [comment]
Yes. I enabled.`node -v` show me `v7.0.0` after `su laradock`. 
why need install global? I have "package.json"
`which node` said `/home/laradock/.nvm/versions/node/v7.0.0/bin/node` 
uglifyjs - `/var/www/symfony/node_modules/uglify-js/bin/uglifyjs`. 
In console `/home/laradock/.nvm/versions/node/v7.0.0/bin/node node_modules/uglify-js/bin/uglifyjs` work.
I set these paths in settings. But it is not work yet. And php `is_file(/home/laradock/.nvm/versions/node/v7.0.0/bin/node)` return false;

**Comment by philtrep** [comment]
@sashaaro I think you're going to have to install node in the `php-fpm` container. The `workspace` is what installs node, I see no reason why your application should be able to find the executable since it doesn't run from `workspace` (it's two separate file systems). You could create a shared volume if you only want a single instance of the executables but that sounds like overkill.

**Comment by sashaaro** [comment]
But I have "package.json". 
I got. Seems I can't do it without instalation node in both containers, sad.

**Comment by philtrep** [comment]
@sashaaro Yes, sadly your use case is pretty specific. If you feel like making PR with your current solution please go ahead. I'm closing this for now.

**Comment by scoutman57** [comment]
I think the proper solution would be to have  container for node and share that. As you would do with any other languages that you need.  @philtrep i agree that this is a pretty specific issue, but in the laravel world it's not that uncommon because there are 11+ million installs of assetic-bundle. I think we need to fix this globally. @Mahmoudz  what do you think?

**Comment by philtrep** [comment]
@scoutman57 I hadn't realized that was such a popular tech.

I can't speak for @Mahmoudz but I think it's a great idea to have a `node` container that makes the executables accessible to all the services.

**Comment by Mahmoudz** [comment]
@scoutman57 @philtrep well yes I thought of that before but wasn't sure how easy and convenient would be to separate Node on it's own container. I think we should try it and find out. 

@scoutman57 feel free to open a new Issue requesting that feature.
