### ISSUE TITLE
Docker Compose working with .env file

### ISSUE THREAD

**Issue by Exadra37** [laradock/laradock#424]
I am willing to work on a Pull Request to add support to read all configurable values in Docker Composer from `.env` file. 

By all configurable values I mean all port and volumes mapping, booleans, Ips, etc.

The `.env` will not be tracked so that we can symlink to the one in our Laravel project, but a `.env-example` will be provided.

This is possible by using the Docker built in support for environment files as we can read [here](https://docs.docker.com/compose/environment-variables/#the-env-file) .

This will allow us to:

* Provide secrets from a `.env` in the host machine securely. This way they are not tracked in Git.
* Not need edit `docker-compose.yml` to meet our needs.
* Run `docker-compose run -e VARIABLE=VALUE container-name entrypoint` to override  `.env`  on per basis needs.

If you agree just :+1: on it.

Let me know your feedback and ideas.

**Comment by Mahmoudz** [comment]
@Exadra37 I like the idea of having a `.env` file since at least will help getting rid of the duplications in the the docker-compose.yaml file (like `INSTALL_MONGO=`, ...). However when someone implemented that in the past we faced wired warnings with every docker compose and docker command.. 

If you are using that solution now and is working just fine with you, we'd love to have it implemented with Laradock. 

Thank you and waiting your PR

**Comment by Exadra37** [comment]
During this weekend I will try to work on this ;)

**Comment by Exadra37** [comment]
This feature is a WIP on my fork, but before i make the PR I need help testing this it...

Please try [this branch](https://github.com/exadra37-docker-forks/laradock/tree/dev/dot-env-file) from my fork.

If you find any bug please open it [here](https://github.com/exadra37-docker-forks/laradock/issues/new).

For feedback and discussion just leave a comment on this current issue.

**Comment by philtrep** [comment]
@Exadra37 You might get better feedback if you create a PR in this repo. Don't worry, if you say it's a Work In Progress we won't merge it without the all clear!
