### ISSUE TITLE
Docker Compose with multiple configuration files

### ISSUE THREAD

**Issue by Exadra37** [laradock/laradock#425]
I am willing to work on a PR to use this built in Docker support to have multiple compose files as we can read [here](https://docs.docker.com/compose/extends/).

One of the best goals of using Docker in Production is to have 100% parity between development, test, staging and production environments.

But during development we may need some tools in top of the Production environment to help us with debug and workflow.

So to achieve 100% parity between environments and at same time have the set of tools we want for development, we must have the `docker-compose.yml` as the base file to be used in **Production** and extend from their to add the tools for **Development** workflow, but **without modifying the Production setup components**.

I mean by not modifying setup components to not switch from `nginx` in production to `apache` in development or from `mysql` to `mariaDb` or from versions of same component.

To set ports and volume mappings, plus Ips, passwords and other values as needed in each environment, the proposal on #424 will address that for us. So we will have the liberty to change this values from `.env` in our Laravel project.

This will allow us to:

* use `docker-compose.yml` as the base production configuration.
* use `docker-compose.override.yml` to use as the production release, because when we run `docker-compose up` it will read the overrides automatically. This file will not be tracked, once must be configured in a per project basis, but a `docker-compose.override.ym-example` will be provided.
* use `docker-compose.dev.yml` that will complement the `docker-compose.override.yml` with the set of tools we only need for development. To boot our dev environment we will do `docker-compose -f docker-compose.override.yml -f docker-compose.dev.yml up`.

If you like the idea please :+1: on it.

Please share your feedback and ideas.

**Comment by Mahmoudz** [comment]
@Exadra37 that sounds like an amazing solution. I'd like to see it in action. Thank you.

**Comment by appleboy** [comment]
Sounds good. 👍

**Comment by Exadra37** [comment]
After I finish the PR for my proposal in #424 I will take on this one :)

**Comment by philtrep** [comment]
@Exadra37 @Mahmoudz I really like this idea but I fear that by modifying the current development usage we'll hit the same problems we had with #339 where user adaptation was difficult.

I personally don't mind writing `docker-compose -f docker-compose.override.yml -f docker-compose.dev.yml up` to start the dev environment however, following `Use Docker first and learn about it later.`, it might be a better idea to keep the dev commands as simple as possible especially since most users use LaraDock only for dev.

Could there be a way to remove needing to specify additional files, keeping `docker-compose up` as the default command? Or if it's not possible we could have a dev up script (something like `./laradock/dev up` as a startup command) to simplify things?

**Comment by Mahmoudz** [comment]
I agree with @philtrep we should have the long commands for production and the simple ones for development (by default). If that possible! Or as suggested a small command would be nice, maybe we contact this guy he created a Laradock CLI https://github.com/logaretm/laradock-cli I never used it by I like the idea.

**Comment by philtrep** [comment]
@Mahmoudz Cool project, this makes me think we should have a section in the docs for LaraDock related projects 😃
