### ISSUE TITLE
Make Laradock more maintanable

### ISSUE THREAD

**Issue by g0ld3lux** [laradock/laradock#550]
As laradock is getting more and more famous, we have more and more pull request that we want to merge...

Well if We really wanna make this the Official Repo...

I Sugguest we make this More Laravel Like...

We Could have a CORE Stacks...

In those Stacks we can Easily Spin Up A Laravel Dev machine...

for example that stack is : php mysql php-fpm redis nginx node

if We Do Intend to Use Extension for example

xdebug , that would be listed in our Plugin Stacks...

I hope you get the Idea...

If we Want this to be Maintable as Possible We Should limit the Core Stacks we Should Use...

Coz not all of them would be Usable in the Same Project...

We Want to Keep only the very basic and extend using Plugins....

Please Let me Here your thoughts thanks

**Comment by philtrep** [comment]
@g0ld3lux Thanks for bringing this up.

As far as being the official repo, this is (as far as I know) something entirely out of our control. It depends on the decision of Taylor Otwell so although we can hope for it (obviously it would make our project/community grow), I don't think we should expect it nor base our long-term planning of this project on it.

That being said I do agree that we need to rethink our approach to how many frameworks/stacks we support and where we want to concentrate our effort.

Maintanability is definitely an issue. One of the problems we are facing is the lack of active support on our side for our less popular images (discussed previously in #368). Pushing in new updates can be often delayed and I know that several of the more active contributors spend quite a bit of time on helping out newcomers instead of adding new features/fixing bugs.

That isn't to say that helping newcomers is not a good way to contribute but we do need more code contributions if we want a more stable project and it does need to be more stable if we want it to be easier to use.

Docker Compose is still a relatively new technology and I can't think of another open-source Docker Compose stack project that does what we are doing. We are in the unfortunate position to be at the receiving end of the errors/bugs that can seep through the several layers of technologies that make running this project possible so I highly doubt that we can be stable AND trendy AND diversified at the same time but we can certainly pick one of those and do it well.

As far as supporting other frameworks, I think it is not a compatible goal with improving our support of Laravel.

What does everybody else think? Obviously @Mahmoudz and @appleboy I'd love to have your opinion on this.

**Comment by appleboy** [comment]
Maybe we can follow the [Contribution Guidelines of Gitea project](https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#maintainers)

> To make sure every PR is checked, we have team maintainers. Every PR MUST be reviewed by at least two maintainers (or owners) before it can get merged. A maintainer should be a contributor of Gitea (or Gogs) and contributed at least 4 accepted PRs. A contributor should apply as a maintainer in the Gitter develop channel. The owners or the team maintainers may invite the contributor. A maintainer should spend some time on code reviews. If a maintainer has no time to do that, they should apply to leave the maintainers team and we will give them the honor of being a member of the advisors team. Of course, if an advisor has time to code review, we will gladly welcome them back to the maintainers team. If someone has no time to code review and forgets to leave the maintainers team, the owners may move him or her from the maintainers team to the advisors team.

**Comment by Mahmoudz** [comment]
@g0ld3lux I like the idea of enhancing the maintainability of the project. 
By Plugins do you mean repository containing a software support?! Can you give us more detailed example on your solution please?

@philtrep @appleboyI do support bringing more maintainers. Maybe @g0ld3lux would like to join us and help us implement his solution to fixing the maintainability issue. @appleboy suggestion (Gitea) looks very nice as a way to organize the PR's, I like to see that happening but I think it's not as easy as it sounds!

**Comment by philtrep** [comment]
@Mahmoudz @appleboy one of the most important parts here is (in my opinion) the support of multiple frameworks. The project has gotten quite big since #76 and I think we should reopen a discussion on wether or not other frameworks should be supported.

As far as the Gitea guidelines, I'm fine with the minimum Contributions to become a Maintainer but the 2 reviewers mandatory would be too hard to implement atm. I already don't have time to do code contributions for LaraDock 😭  and I think it's the same with you guys...

**Comment by mikeerickson** [comment]
@philtrep @Mahmoudz @appleboy 

I completely agree! Also, leads to some "confusion" based on the name `laradock` I am thinking, if this project wants to be the `official` docker package for Larevel, it should stay focused to laravel.  

I am willing to help the cause best I can.  @philtrep knows my work (with the two recent PRs)

**Comment by appleboy** [comment]
@philtrep @Mahmoudz @mikeerickson

Maybe we need to create another repo to handle other frameworks and make this repo to be the official docker package to Laravel. Find more maintainer to handle another framework issue or there are many issues on another framework like (CodeIgniter or ...)

**Comment by mikeerickson** [comment]
@philtrep @Mahmoudz @appleboy 

I am primed to help maintain / triage this repo as I only use Laravel for PHP work

**Comment by philtrep** [comment]
Just to keep this issue update, @mikeerickson has been added to the admin team and the issue tags have been updated for clarity.
