### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by theseanstewart** [LaraDock/laradock#57]
Getting this error on a fresh docker machine when accessing my site:

`RuntimeException in EncryptionServiceProvider.php line 29:
No supported encrypter found. The cipher and / or key length are invalid.`

I've tried generating a new key, clearing cache, recompiling, restarting the containers, etc. This exact same project works flawlessly on my Vagrant box. 

Any ideas?

**Comment by Mahmoudz** [comment]
The error is very clear, you just have to generate a valid key in your `.env` file. Check your `.env` file and if the key it's empty try adding it manually.

**Comment by theseanstewart** [comment]
Yes, the error is clear, which is why I mentioned in the original post that I tried generating a new key. Maybe I should have been more clear. 

I have confirmed that it is set in the .env file. I tried manually setting it in app/config.php. I confirmed that it was set by running php artisan tinker and outputting the value of env('APP_KEY'). 

I also just created a new Laravel project from scratch. Same error.

**Comment by Mahmoudz** [comment]
mmm that's very wired!! you said the exact same project works flawlessly on your Vagrant box but not on Docker! not sure if I'm missing any PHP extension! but I've never faced this error myself, are you using the default encryption driver? because all the defaults used to work just fine with everyone!!
Anyway we'll leave this Issue opened maybe someone facing the same error can help.
Best of luck.

**Comment by mattythebatty** [comment]
Could you try doing `docker-compose up --force-recreate --build` when you start it?

Also, could you put `phpinfo()` at the top of the public/index.php file and print the result?
