### ISSUE TITLE
How to change MySQL port

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#571]
I am trying to change the port used by my docker container (followed installation instructions) but it always throw an error (I am sure I am missing a step somewhere, but I have followed documentation)

```
docker-compose up -d nginx mysql
```

Error message

```
Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated
```

- [x] Edited `mysql/my.cnf` 
        ```
        [mysqld]
        port=3308
        ```
- [x] Edited `docker-compose.yml`
        ```
        ports:
               - "3306:3308"
        ```

---

**Comment by Lednerb** [comment]
Hi @philtrep 

it seems that you have already a running container with port binding to 3306.

Furthermore if you want to change the port of your container you have to edit the first one like this:
```
Edited mysql/my.cnf
[mysqld] port=3306

Edited docker-compose.yml
ports: - "3308:3306"
```

**Comment by francislavoie** [comment]
Or better, just use `expose` instead of `ports` if you don't plan on needing to connect to your mysql database from the host. If you're only going to be using it from an application within your docker stack, there's no reason to bind the port on the host. If you're going to use it in production, it's even more important that you DON'T use `ports` and instead use `expose` for services like mysql. Only your web-facing services (nginx, apache, caddy, etc) should have their ports bound (i.e. 80 and 443 for HTTP and HTTPS respectively). Otherwise, anyone could connect to your mysql container from the outside world (if they have the password, which they could brute-force if they wanted to).

**Comment by philtrep** [comment]
@francislavoie We tried removing port binding for mysql a few months ago but we then reverted the change because of complaints. The default docker compose file MUST NOT be used in production. You can see my old PR about port binding #339.

**Comment by Farnan130117** [comment]
Why this type of issue is closed ! even if the issue is still same. 
I am facing this type of conflict. 
Using Laradock.io , facing conflict between 3306 port for mysql container. 
Inside laradock --> Having port number 3306 in
 (
 mysql folder -> my.cnf & Dockerfile
docker-compose.yml file
.env file 
) 
in those file used 3306 so many times. 

I am being confused. How to solve this , no exact solution.

**Comment by diego1campos** [comment]
> Why this type of issue is closed ! even if the issue is still same.
> I am facing this type of conflict.
> Using Laradock.io , facing conflict between 3306 port for mysql container.
> Inside laradock --> Having port number 3306 in
> (
> mysql folder -> my.cnf & Dockerfile
> docker-compose.yml file
> .env file
> )
> in those file used 3306 so many times.
> 
> I am being confused. How to solve this , no exact solution.

I totally agree, what I did is not technical at all but practical and worked. I used sublime text "find in files" tool 
(you can use another IDE/editor/programm) to I looked up 3306 and replaced the coincidences in these files:

C:\Users\dcampos\doc\.env:

C:\Users\dcampos\doc\config\database.php:

C:\Users\dcampos\doc\docker-compose.yml:

C:\Users\dcampos\doc\laradock\.env:

C:\Users\dcampos\doc\laradock\docker-compose.yml:

C:\Users\dcampos\doc\laradock\mariadb\Dockerfile:

C:\Users\dcampos\doc\laradock\mariadb\my.cnf:

C:\Users\dcampos\doc\laradock\mysql\Dockerfile:

C:\Users\dcampos\doc\laradock\mysql\my.cnf:

C:\Users\dcampos\doc\laradock\percona\Dockerfile:

C:\Users\dcampos\doc\vendor\laravel\sail\bin\sail:

C:\Users\dcampos\doc\vendor\laravel\sail\stubs\docker-compose.yml:

I'm super intelligent I know jeje
