### ISSUE TITLE
make data volumes permanent

### ISSUE THREAD

**Issue by FrodeMMeling** [laradock/laradock#599]
Noob question here. I see volume definitions at the bottom of the docker-compose file.
How can I map mysql and other databases to permanent local folders, so they survive a container rebuild.

**Comment by francislavoie** [comment]
It used to be this way, but it was changed in this commit: https://github.com/laradock/laradock/commit/9ab6d8fa15f1ed7de277b0838c847193a7b971db

You can do this `./data/mysql:/var/lib/mysql` on your mysql volume for it to persist. With the current implementation, it does persist, but it gets put somewhere in `/var/lib/docker`, which is relatively tedious to access.

@Mahmoudz why the change to volumes_data to use the local volume driver instead of just mounting it into folders in `./data`? That seemed like the saner solution for new users. Volume drivers are definitely confusing.

**Comment by rg-srini** [comment]
Yes. I agree with @francislavoie. Volume drivers are definitely confusing.

**Comment by bestlong** [comment]
Hi @FrodeMMeling Currently, laradock default save database data at host os.
you can check `.env` config file parameter `DATA_SAVE_PATH=~/.laradock/data`

**Comment by ko1eda** [comment]
Not really sure where else to post this but where exactly are the named volumes in laradock stored on windows? What is ~/.laradock/data I have no idea what or where that directory is

**Comment by elkun310** [comment]
> ot really sure where else to post this but where exactly are the named volumes in laradock stored on windows? What is ~/.laradock/data I have no idea what or where that directory is
Can i get data with .sql file from this folder in path ~/.laradock/data , bro ?
