### ISSUE TITLE
mariadb port conflicted 3306

### ISSUE THREAD

**Issue by litan1106** [laradock/laradock#620]
To reproduced the problem. 

docker-compose stop && docker-compose up -d nginx mariadb mongo redis phpmyadmin

ERROR: for mariadb  Cannot start service mariadb: driver failed programming external connectivity on endpoint laradock_mariadb_1 xxx: Bind for 0.0.0.0:3306 failed: port is already allocated

To fix the error: I had to change the mysql port to 33061.

**Comment by scoutman57** [comment]
Are you running a local (host) install of mysql/mariadb or any other mysql drop-in replacement? I bet you are. If so that is why you get the conflicts. Or you have another container using that port. It's not uncommon to have to change those. I run several containers and a local host version of things so I have to modify all the ports anyways.  This is not a bug, just normal issues you would have any time.

**Comment by francislavoie** [comment]
Change `ports` to `expose` and `3306:3306` to `3306` under `mariadb` in your `docker-compose.yml` if you don't need direct access to your database from your host.
