### ISSUE TITLE
workspace container is missing postgress driver

### ISSUE THREAD

**Issue by AminMkh** [LaraDock/laradock#63]
I get the following when I try to migrate the database on postgres.

```
root@bc0a9189bfdd:/var/www/laravel# php artisan migrate:refresh --seed                    
  [PDOException]         
  could not find driver  
```
It's missing the postgres driver, though the PHP-FPM one is installed fine, it's an easy fix, but I'm struggling with multiple pull requests, I keep missing up and getting all commits into one PR.

```
RUN docker-php-ext-install pdo_pgsql
```

**Comment by Mahmoudz** [comment]
Hi @AminMkh, 

thanks again for the great effort you make in contributing to LaraDock.

Yes we are missing the Postgres extension on the Workspace container. 
Postgres will work from the app since it's only installed on the PHP-FPM container. But will not work from the artisan command line, since it's not installed on the PHP-CLI in the Workspace container.

Regarding the PR's just make a new branch for every change/fix/feature and push that branch to your forked copy, then switch to your local master branch and from it create another new branch and so on (it's very important if you're working on FeatureA branch to switch back to the Master branch and then create FeatureB branch, never go directly from FeatureA to FeatureB because in that case you will still have the changes of FeatureA in your FeatureB which cases the exact same problem you are currently facing). At any time you can create new PR from each of the branches on your github to the Master branch on LaraDock.

Best,
