### ISSUE TITLE
Mount volumes in the 'workspace' container with RW access

### ISSUE THREAD

**Issue by andr2k** [laradock/laradock#657]
I am new to Docker, so excuse me in advance please.

1. Install Laradock, start everything
2. Run bash from the 'workspace' container: `docker-compose exec --user=laradock workspace bash`
3. Do `ls -la` from `/var/www`:

```
laradock@424d5e8d79aa:/var/www$ ls -la
total 180
drwxr-xr-x 11 nobody nogroup  4096 Mar  7 14:54 .
drwxr-xr-x 30 root   root     4096 Mar  7 12:21 ..
drwxr-xr-x  4 nobody nogroup  4096 Feb 17 00:42 app
drwxr-xr-x  2 nobody nogroup  4096 Mar  7 14:54 bin

```

Result: all folders and files belong to `nouser:nogroup`.

Check current user id inside the workspace:
```
laradock@424d5e8d79aa:/var/www$ id
uid=1000(laradock) gid=1000(laradock) groups=1000(laradock)
```

Check the id and other info inside the host:
```
$ id
uid=1000(user) gid=1000(user) groups=1000(user)

$ docker --version
Docker version 17.03.0-ce, build 60ccb22

$ docker-compose --version
docker-compose version 1.11.1, build 7c5d5e4
```

I see that Dockerfile for the 'workspace' container has commands for adding laradock user and group. My uid/guid are 1000 as well.

This means that I cannot make changes in the filesystem without changing file attributes to less secure (like 777).  For instance, `composer install` cannot create `vendor` folder etc. Is there a way to mount everything while being able to change files from the container?

**Comment by andr2k** [comment]
Possibly, something is wrong with my docker configuration, because even a pure docker example does not work as expected: 

```
docker run --rm -it -v ~/.bash_history:/root/.bash_history ubuntu /bin/bash
```

Source: https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume

**Comment by philtrep** [comment]
@andr2k Since the docker example is not working I'd try removing Docker from your machine and reinstalling it. I don't think this is specifically linked to Laradock, if reinstalling doesn't fix your issue I'll reopen the issue.

**Comment by zwz111** [comment]
me too
Install Laradock, start everything
Run bash from the 'workspace' container: docker-compose exec --user=laradock workspace bash

laradock@ad5b6b116635:/var/www$ id
uid=1000(laradock) gid=1000(laradock) groups=1000(laradock)

laradock@ad5b6b116635:/var$ ls -la
drwxr-xr-x. 3 root root  17 Mar 19 01:38 www

www do anything  Permission denied


docker host :centos 
linux promote.cache-dns.local 4.10.2-1.el7.elrepo.x86_64 #1 SMP Sun Mar 12 13:25:09 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

# docker --version
Docker version 17.03.0-ce, build 3a232c8

docker-compose --version
docker-compose version 1.11.2, build dfed245


Is it because I disable SELinux?

**Comment by zwz111** [comment]
I think I know the problem...

Because I also set the /var/www to APPLICATION
I gave him a set to APPLICATION=../ normal   its absolute path is /home/xxx
(:

**Comment by andr2k** [comment]
This it is not a bug: https://github.com/docker/docker/issues/31689
