### ISSUE TITLE
Prod config example docker-compose-prod.yml

### ISSUE THREAD

**Issue by sashaaro** [laradock/laradock#668]
Hi everyone. Someone use it in producation?
What about setup example configuration for producation environment?
I have problem and I worry about delivery services to server.
Purpose make deploy proccess faster and safe.
How I see in producation run only `docker-compose pull` and `restart` (not care about source code like git pull). Seems we need copy source code to containers instead of make volumes. And hook start scripts for run db migrations after.

**Comment by Mahmoudz** [comment]
@sashaaro we tried that before, but it was hard me and most contributors to remember updating both files. So I deleted that file #524 and we were supposed to replace it with documentation section. But no one ever did that since then, if you spend time finding answers and getting it to work, w'll appreciate of you can add a section in the docs about that. Thanks,
