### ISSUE TITLE
[Question] Is there benefit using PHP-PM with docker/laradock?

### ISSUE THREAD

**Issue by a-h-abid** [laradock/laradock#718]
None from gitter.im answered my question so asking here.

I see this [PHP-PM](https://github.com/php-pm/php-pm) thing saying that it improves performance by a lot. I guess that If I use it directly on my machine that it would have high performance. But since I'm using laradock, there might be performance issue or I may not get that benefit that it claims.

So want to know is it going to be any useful to use php-pm with laradock/docker? Also would help if a sample is shown how to use it with laradock.

**Comment by thorerik** [comment]
php-pm is highly experimental, it works by essentially pre-initializing the framework and serving each request on it's own through the pipeline of $framework (laravel/silex/symfony/insert other supported framework here).

The downside is that it will exasperate any memory leaks, since the process never ends (iirc. doctrine isn't all that great at cleaning up after itself for example).

From a technical standpoint, there shouldn't be any issues using it with laradock, but you'll have to swap out FPM for PM (creating your own container that replaces it).

I wouldn't recommend using php-pm or similar projects just yet, they are in their early infancy, few need that kind of performance improvements anyways (you're probably not serving millions of requests a hour/day), in which case, it's easier to roll load balanced, and it gives you some other benefits like fault tolerance as well.

**Comment by a-h-abid** [comment]
I see. Thanks for the answer @thorerik .

I think I'll try to check it myself sometime later as an experiment and see what it does. It is would be nice if this progresses further and becomes stable to use in our applications.

For now, I'll stick to using load balancer.
