### ISSUE TITLE
Directory/file ownership (root/laradock)

### ISSUE THREAD

**Issue by kp77** [laradock/laradock#753]
I'm trying to change directory/file ownership to laradock user but chown doesn't do anything. Everything is owned by root in `/var/www` and if I create something new as laradock user it will be owned by root.

I have problems with npm install because of this.

I think this is a similar issue: #373

**Comment by Mvzundert** [comment]
@Mahmoudz There's also something going on with NFS sharing on OSX.

**Comment by kp77** [comment]
I'd like to add, that while the original issue still exists (all files are owned by root and it can't be changed via chown), it seems that I can use the www directory logged in as laradock without problems.

I'm logged in as laradock, but I have write access to the files/directories owned by root, although I should not have write access according to the permission settings.

**Comment by MikSDigital** [comment]
Hi! 

I am using Laradock under Ubuntu 16.04 with Docker version 17.03.1-ce, build c6d412e.

And have also user/permissions problem:

`m@homePC:~/docker/laradock-testing/my_project_test$ ls -la
total 136
drwxr-xr-x  9 root root  4096 apr   16 19:34 .
drwxrwxr-x 14 m    m     4096 apr   16 19:34 ..
drwxr-xr-x  4 root root  4096 apr   16 19:34 app
drwxr-xr-x  2 root root  4096 apr   16 19:37 bin
-rw-r--r--  1 root root  2379 apr   16 19:34 composer.json
-rw-r--r--  1 root root 78082 apr   16 19:34 composer.lock
-rw-r--r--  1 root root   248 apr   16 19:34 .gitignore
-rw-r--r--  1 root root  1065 apr   16 19:34 LICENSE
-rw-r--r--  1 root root   978 apr   16 19:34 phpunit.xml.dist
-rw-r--r--  1 root root  2300 apr   16 19:34 README.md
drwxr-xr-x  3 root root  4096 apr   16 19:34 src
drwxr-xr-x  3 root root  4096 apr   16 19:34 tests
drwxr-xr-x  5 root root  4096 apr   16 19:37 var
drwxr-xr-x 15 root root  4096 apr   16 19:37 vendor
drwxr-xr-x  3 root root  4096 apr   16 19:37 web
`

**Comment by gabriellucius** [comment]
Same problem here, and if I run chmod the with laradock or root user anything changes :(

**Comment by morales2k** [comment]
I'm running windows and this issue cropped up as well. 

Running chmod on anything returned no errors, but no expected results either. Just like @gabriellucius described.

I ssh'd into the workspace container using the laradock user, and ran composer install on my project. It did not error out on permissions, it created the vendor folder, and it installed my dependencies. 

Yes, with laradock user, and permissions being `root:root` on everything as described by @MikSDigital.

I don't blame you if you don't believe what I am describing here, but it is as I'm saying it. Since it is working, I'm not going to mess with it any longer... but it sure rubs me in all the wrong ways imaginable to see root on the group and user permissions, and then be able to write on those folders with a laradock user that, according to `Dockerfile-72` (I'm using php 7.2) belongs to the `laradock:laradock` permission set... 

My mind is still blown... but then I remember this is Windows and it kinda makes sense... 
Kind of...
