### ISSUE TITLE
More than one laravel project

### ISSUE THREAD

**Issue by Bahad001** [LaraDock/laradock#8]
i want to develop more than laravel project in the same time in the laradock docker...
how can i do this...

**Comment by Remuwon** [comment]
It depends on your setup. Do you want to reuse the containers or to create new ones. For the former you can just clone the repo for your new project. Once the containers are created for the very first time you'd just have to run docker-compose start and the containers would be reused. Just a side note, since the mysql and redis containers share the same data volume; it means all your databases and their data will be on the same container.

If you want to create new containers just clone/(fork then clone) and modify the docker-compose.yml till your heart is content :). Side note, you don't want conflicting container names so make sure they are unique.

When you are switching between projects you might want to stop the container then put it up again from your new project folder.

**Comment by petergit67** [comment]
Im new to Docker but i really like your LaraDock and i cant get it to work width many sites/domains.

Please guide me so i can use LaraDock as my development instead of Vagrant.

Thank you.

**Comment by petergit67** [comment]
Hi again,

I solved this by adding more hosts/roots in default file under settings.

Is this an okay solution?

**Comment by Mahmoudz** [comment]
I highly recommend that you check the lates release https://github.com/LaraDock/laradock/releases It might solve your problem.

**Comment by petergit67** [comment]
Sweet, thank you.

Med vänlig hälsning

Peter Carlsson
*Digital IT*
Vxl: 08-501 235 69
Mob: 0708-28 23 28
Web: www.digitalit.se <http://www.digitalit.se>
Den 2016-02-17 kl. 17:30, skrev Mahmoud Zalt:

**Comment by luis-don-dev** [comment]
How did you solve it? I can't figure out how to do it. Any help would be very appreciated (:

**Comment by Mahmoudz** [comment]
@luis-don-dev I'll answer you on your new issue #54
