### ISSUE TITLE
Don't use the latest adminer (4.3.1) for docker container

### ISSUE THREAD

**Issue by zeroc0d3** [laradock/laradock#813]
I've tested using adminer for early version using 4.3.1 (the latest) for docker container. 
Bugs founded when i'm trying to login for PostgreSQL, issue had been reported 
https://sourceforge.net/p/adminer/bugs-and-features/548/

I suggest to use the old version adminer version 4.3.0.

**Comment by partounian** [comment]
To do this, go to adminer/Dockerfile and change 
`FROM adminer:latest` to `FROM adminer:4.3.0`
As I introduced adminer here, I hope I can help others with any problems they may be having.

**Comment by winfried-van-loon** [comment]
Should this be changed in the relevant files or should this information be introduced into the Laradock docs?

**Comment by partounian** [comment]
Probably add it into the docs or FAQ if there is one.

**Comment by winfried-van-loon** [comment]
After some consideration, and taking into account that Laradock should be simple to use (it should "just work"), I've added it in both the docs and the Dockerfile in question with the explanation included.

Adminer [seems to release a new version monthly](https://sourceforge.net/p/adminer/news/), it's possible it'll be fixed in just a few weeks, but in that time, more people may come across this issue.

**Comment by zeroc0d3** [comment]
Yes... absolutely right.
No need to wait so long until this bug fixed. We just use the old stable version in 4.3.0.
