### ISSUE TITLE
Can not connect to database server after change default .env file

### ISSUE THREAD

**Issue by ibenchu** [laradock/laradock#830]
Can not connect to database server after change default .env file
```
### POSTGRES Container
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=bc123
POSTGRES_PORT=5432
```

```
host : IP
DB: postgres
USER: postgres
PASSWORD:bc123
```
error info:

```
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | FATAL:  password authentication failed for user "default"

```

**Comment by bestlong** [comment]
@ibenchu because you last time up postgres container init db step already done.
if you don't mind remove all postgres data, you can delete it by command:
```
rm -rf /tmp/postgres
```
then up postgres container, new password will be applied.

if you want to keep postgres data, you can up with adminer container, use web gui to login by old password and change it.
