### ISSUE TITLE
can't connect to localhost

### ISSUE THREAD

**Issue by heinhoang** [laradock/laradock#866]
- Windows 10
- Docker version 1.13.1, build 092cba3
I follow tutorial http://laradock.io/#B (Setup for Multiple Projects). But I can't connect to localhost. It says:
```
This site can’t be reached
localhost refused to connect.
```
I navigate to http://192.169.99.100/. It says:
```
Bad Request (Invalid Hostname)
```
I tried to find `DB_HOST`  in '.env' (which is copied from 'env-example' file) but there's no `DB_HOST`  string in '.env' file.

**Comment by dtunes** [comment]
Hi,

so you've created a file under nginx/sites/mysite.conf? e.g. mysite.dev

If so, create a dns entry in your hosts file.

127.0.0.1 mysite.dev

The DB_HOST variable is not set in the env-example, because that's a project specific variable. You need to set it under your e.g. Laravel/Lumen project's .env file. http://laradock.io/getting-started/#Usage Look right at the bottom.

4 - Update your project configurations to use the database host
Open your PHP project’s .env file or whichever configuration file you are reading from, and set the database host DB_HOST to mysql:
DB_HOST=mysql

**Comment by nanophp** [comment]
Use docker-machine ip and then you'll get an ip address. I just try like this and can get reach the site.
