### ISSUE TITLE
laravel dusk in multiple projects setup

### ISSUE THREAD

**Issue by lx-berlin** [laradock/laradock#907]
### Info:
- Docker version (`$ docker --version`): 17.05.0-ce, build 89658be 
- Laradock commit (`$ git rev-parse HEAD`): 100a2eb4aef63e870560b5d9d28851e359a79e1f
- System info (Mac, PC, Linux): Linux

##### What seems to be going wrong?

I have laradock for multiple projects installed.
In the workspace container I am trying to run 
`php artisan dusk`

In .env.dusk.local I configured
`APP_URL=http://myproject.dev` 

But I cant get the test to run.
What am I missing to run dusk in this multiple project setup ?

Thanks

**Comment by CharlieTapSonin** [comment]
By multiple projects do you mean that your laravel project actually serves more than one site? 

Assigning APP_URL to http://myproject.dev will not work unless you've configured a link on your selenium container pointing that hostname at your nginx container. PHP forwards the requests to selenium which passes that url on to chrome, chrome's DNS lookup will need to find a mapping from that url to the nginx container. I actually run multiple sites from one project and ran into this so here's the solution:

 selenium:
      image: selenium/standalone-chrome
      volumes:
        - /dev/shm:/dev/shm
      expose:
        - "9000"
      depends_on:
        - nginx
      links:
        - nginx:http://myproject.dev
        - nginx:http://secondproject.dev
        - nginx:http://thirdproject.dev

**Comment by lx-berlin** [comment]
thanks! This does the trick.
Only, I had to change
```
links:
- nginx:http://myproject.dev
```

to:

```
links:
- nginx:myproject.dev
```

because otherwise i got 

_ERROR: for selenium  Cannot start service selenium: bad format for links: laradock_nginx_1:http://myproject.dev
ERROR: Encountered errors while bringing up the project._

**Comment by lionslair** [comment]
Sweet. I was having no luck running dusk tests this solved it.

**Comment by ezekel** [comment]
@CharlieTapSonin ,

where do we declare those links ? please help me I want to use laravel dusk, I'm done with the installation following here  https://laravel.com/docs/6.x/dusk

Thank you in advance.

**Comment by lionslair** [comment]
@ezekel under selenium 

![Selection_006](https://user-images.githubusercontent.com/832259/75334087-3687f180-58c2-11ea-952b-b38f7452dad4.png)

but I am getting white screen all the time today

**Comment by ezekel** [comment]
@lionslair ,

Do you also execute command php artisan serve ? because if I will not do that command the laravel dusk cannot see my project.

**Comment by lionslair** [comment]
No I don't run php serve. I do however run the `dusk path/to/file --filter test_name_here` from within the workspace.

SSH into the workspace then run dusk. No need to use serve

All has been working fine for months. However I have the issue now where I was working on getting php updated to php 7.4 across the containers. Didn't finish it though. I switch back to my master branch and rebuilt all again and now chrome has updated to version 80.

So I now get 
![Screenshot from 2020-02-26 18-13-44](https://user-images.githubusercontent.com/832259/75400062-11829580-5939-11ea-8b5d-416131c2f33b.png)

But this is because I am using local over https and so now I have to add a flag to skip it in my dusk driver. Not as simple as I thought.

**Comment by ezekel** [comment]
@lionslair ,

Thanks, I'll be back on this dusk.. hope you'll find solution.

**Comment by ezekel** [comment]
@lionslair ,

can I ask what is `caddy` ? you declared in your links ? cadd:screensavers.test
