### ISSUE TITLE
Development environment : Laravel 5 is super slow with docker and Oracle VM on windows (SSD)

### ISSUE THREAD

**Issue by vinaykevadia** [LaraDock/laradock#97]
i am unable to use laradock for my development environment. its very slow.

**Comment by tristanbailey** [comment]
It is likely to be the speed of your computer + VM + free memory that will affect speed

**Comment by vinaykevadia** [comment]
Thanks @tristanbailey , but i am having i5 processor, with 8GM memory and SSD. hardware configuration looks good to me. one of my friend was saying it might be because of shared IO is slow between VM and host. i had fixed the same issue in vagrant by altering two lines of configurations but not sure how to fix it with Docker.

**Comment by AminMkh** [comment]
well I can say that I went through the same experience, 
Windows then VirtualBox then Docker is very slow in my experience, docker on linux(ubuntu for instance is wayyy faster and almost feels like native nginx/mysql/php app on linux).

However I do think that docker for windows/mac beta is gonna improve performance a lot.

**Comment by andrewmclagan** [comment]
Yeah it does🤗 I use it

**Comment by Mahmoudz** [comment]
Let's hope the Docker Native will solve this. [DOCKER](https://www.docker.com/products/docker).

**Comment by andrewmclagan** [comment]
As stated above, Im using docker for mac beta for the last month. Its lighting quick. Vagrant does not even compare. For those on windows or a non-unix system, not really sure whats happening in that sphere, development always tend to move allot slower... Consider moving to a real "developers" OS ;-)

**Comment by citosid** [comment]
@andrewmclagan I'm using native docker and it is slow. I takes over a second to load a simple hello world page. Do you have any idea if there is any tweak needed after following the how to?

**Comment by andrewmclagan** [comment]
When you say native docker are you running on a linux kernal and not osx? There is no true native docker binary for osx, even docker-for-mac uses a very lightweight virtual machine image.

Although response times of over a second are not normal. What are your response times when these containers are running on a linux host in the cloud? That way you can isolate the problem to Docker on osx. If the response times are still very slow on a pure linux host then your problem is with your application code. One weakness of laravel is the amount of files it loads into memory on each request. Make sure you are enabling `opcache` 

I have my onw image we use in production, we run over 300 containers with Laravel inside them and its lightning fast `20ms-80ms`. take a look:

https://github.com/andrewmclagan/aphex

Alpine PHP Nginx

You will have to create your own nginx.conf as our one is optimised for a pure JSON API not serving HTML.

**Comment by citosid** [comment]
@vinaykevadia I did try using `docker-machine` instead and the speed is way different. It is faster with the virtualbox approach. I did not know that there is no real `native` docker for macOS. 

Thank you for the feedback though, I really appreciate. Will keep testing docker.

Thanks!

**Comment by andrewmclagan** [comment]
@citosid Seriously, if you are getting such bad performance I'd say it more likely points to your setup. Not the `Docker >> Host >> VirtualMachine` interface, it just becomes more easily recognisable in this situation. Are you loading allot of services providers you dont need? Caching your routes? Caching your config?

**Comment by citosid** [comment]
@andrewmclagan thank you for the help. I think I did not explain myself correctly.

If I use docker-machine instead the site loads a lot faster. Which I think it is ok, because in this way I'm using a really native docker. But this means spinning up a virtual machine, which is what I want to avoid.

About laravel, I do not have other than the default installation. That means, not service providers, not routes, not config. Not other than the default ones. 

My test is this:

1. Test with virtual machine using it with homestead. Time to load default page: < 250ms
2. Test with docker (using docker binary for mac): Time to load default page: > 1s
3. Test with docker-machine (using a virtual box): Time to load default page: < 500ms

As you can see, the tests with docker itself take longer, but I think it is ok because I'm using it in a Mac. 

At the moment I'm ok using it in a virtual box (with docker instead of homestead), but that is what I want to get rid of.

I found [this][1], so I guess that is a _normal_ problem with OS and Docker...


[1]: https://forums.docker.com/t/alternatives-to-osxfs-performant-shares-under-osx/19565

**Comment by andrewmclagan** [comment]
Ok understod :)

Im using docker-for-mac with a very very heavy Laravel installation, more then double the dfault service-providers and allot of other custom code. We get between 70ms - 400ms to load a route.

This is far faster when the same container is deployed onto a linux host.

Please realise that docker-for-mac and docker-machine BOTH use virtual machines. The only difference is that docker-machine uses teh much slower virtualox driver rather then xyve
