### ISSUE TITLE
Mysql Access denied for user 'root'

### ISSUE THREAD

**Issue by ihd2911** [laradock/laradock#991]
This is my .env file mysql settings

MYSQL_DATABASE=rds
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root

Following is docker-compose
mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes_from:
        - applications  
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      expose:
        - "3306"
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

When i up container and go inside container and try to connect to mysql from there i get error 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by slackmous** [comment]
Can you delete /tmp/mysql and run docker-compose build mysql then run docker-compose up -d nginx mysql and try again?

**Comment by datpp** [comment]
hi @ihd2911 

please try to connect MySQL with TCP protocol (it mean replace localhost by 127.0.0.1)

**Comment by ryancwalsh** [comment]
I'm brand new to Docker as of yesterday. I gave up trying to get Laradock working on Docker Toolbox since the documentation is all messed up. I created a DigitalOcean account and installed Laradock there. 

I _think_ everything is working other than: I'm having trouble logging into my MySql DB within the `laradock_mysql_1` container.

I bet it's related to: https://github.com/laradock/laradock/issues/1260 I will keep trying and follow up there.
